// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e6a18c461da2c31bd3854d90a068c14c4ffb67f3a73f23fe765dad50d70c4266
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import TreeSitterLanguagePack
import RustBridge

/// E2e tests for category: parsing.
final class ParsingTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testParsingGoFunction() throws {
        // Parse a Go function declaration and assert node type
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"go\"}")
        _ = try TreeSitterLanguagePack.process(source: "package main\nfunc main() {}", config: configObj)
    }

    func testParsingHtmlElement() throws {
        // Parse an HTML element and assert node type
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"html\"}")
        _ = try TreeSitterLanguagePack.process(source: "<div>hello</div>", config: configObj)
    }

    func testParsingJavascriptClass() throws {
        // Parse a JavaScript class declaration.
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"javascript\"}")
        _ = try TreeSitterLanguagePack.process(source: "class Foo { bar() {} }", config: configObj)
    }

    func testParsingJavascriptVariable() throws {
        // Parse a JavaScript variable declaration and assert node type
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"javascript\"}")
        _ = try TreeSitterLanguagePack.process(source: "const x = 1;", config: configObj)
    }

    func testParsingPythonFunction() throws {
        // Parse a Python function definition and assert node type
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"python\"}")
        _ = try TreeSitterLanguagePack.process(source: "def hello(): pass", config: configObj)
    }

    func testParsingRustFunction() throws {
        // Parse a Rust function definition and assert node type
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"rust\"}")
        _ = try TreeSitterLanguagePack.process(source: "fn main() {}", config: configObj)
    }

    func testParsingRustStruct() throws {
        // Parse a Rust struct definition.
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"rust\"}")
        _ = try TreeSitterLanguagePack.process(source: "struct Point { x: f64, y: f64 }", config: configObj)
    }

    func testParsingTypescriptFunction() throws {
        // Parse a TypeScript function with type annotations and template literal return
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"typescript\"}")
        _ = try TreeSitterLanguagePack.process(source: "function greet(name: string): string { return `hi ${name}`; }", config: configObj)
    }

}
