# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:976e3b6b83d187cee6bb9dd6b0b8644f15198c5e45d5a66a3b2d2f7573374a9d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.ByteRange do
  @moduledoc "A byte range — start (inclusive) to end (exclusive)."

  @typedoc "A byte range — start (inclusive) to end (exclusive)."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer()
        }

  defstruct start: 0,
            end: 0
end
