# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:14687d1c1d0c2f444a287af8e41bb8e299062b27c46c2720ef9c04d1c12dc6d0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.ByteRange do
  @moduledoc "A byte range — start (inclusive) to end (exclusive)."

  @typedoc "A byte range — start (inclusive) to end (exclusive)."
  @type t :: %__MODULE__{
  start: non_neg_integer(),
  end: non_neg_integer()
  }

  defstruct start: 0,
  end: 0
end
