# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a023f35f8248a79aed5fb81fb746e8a495ec5dc144ed925957c15f8b8ca7ec0a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.ByteRange do
  @moduledoc "A byte range — start (inclusive) to end (exclusive)."

  @typedoc "A byte range — start (inclusive) to end (exclusive)."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer()
        }

  defstruct start: 0,
            end: 0
end
