# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:68c1122c5e9d4625ff17b3ac284750a02712852755f684b5b6e201b2b98a2694
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.ChunkContext do
  @moduledoc "Metadata for a single chunk of source code."

  @typedoc "Metadata for a single chunk of source code."
  @type t :: %__MODULE__{
  language: String.t() | nil,
  chunk_index: non_neg_integer(),
  total_chunks: non_neg_integer(),
  node_types: [String.t()],
  context_path: [String.t()],
  symbols_defined: [String.t()],
  comments: [TreeSitterLanguagePack.CommentInfo.t()],
  docstrings: [TreeSitterLanguagePack.DocstringInfo.t()],
  has_error_nodes: boolean()
  }

  defstruct language: nil,
  chunk_index: 0,
  total_chunks: 0,
  node_types: [],
  context_path: [],
  symbols_defined: [],
  comments: [],
  docstrings: [],
  has_error_nodes: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
