# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:14687d1c1d0c2f444a287af8e41bb8e299062b27c46c2720ef9c04d1c12dc6d0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.CodeChunk do
  @moduledoc "A chunk of source code with rich metadata."

  @typedoc "A chunk of source code with rich metadata."
  @type t :: %__MODULE__{
  content: String.t() | nil,
  start_byte: non_neg_integer(),
  end_byte: non_neg_integer(),
  start_line: non_neg_integer(),
  end_line: non_neg_integer(),
  metadata: TreeSitterLanguagePack.ChunkContext.t()
  }

  defstruct content: nil,
  start_byte: 0,
  end_byte: 0,
  start_line: 0,
  end_line: 0,
  metadata: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
