# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c4755e5e223f2023d4c34684c2117011d276309e44950a0bd474f1f25564f695
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.CodeChunk do
  @moduledoc "A chunk of source code with rich metadata."

  @typedoc "A chunk of source code with rich metadata."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          start_byte: non_neg_integer(),
          end_byte: non_neg_integer(),
          start_line: non_neg_integer(),
          end_line: non_neg_integer(),
          metadata: TreeSitterLanguagePack.ChunkContext.t()
        }

  defstruct content: nil,
            start_byte: 0,
            end_byte: 0,
            start_line: 0,
            end_line: 0,
            metadata: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
