# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:976e3b6b83d187cee6bb9dd6b0b8644f15198c5e45d5a66a3b2d2f7573374a9d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.CommentInfo do
  @moduledoc "A comment extracted from source code."

  @typedoc "A comment extracted from source code."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          kind: String.t() | nil,
          span: TreeSitterLanguagePack.Span.t(),
          associated_node: String.t() | nil
        }

  defstruct text: nil,
            kind: :line,
            span: nil,
            associated_node: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
