# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fa25725a6cbadfc12d71766f7c83702ecf6837346d63834ccccc550e3359b9bd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.CommentInfo do
  @moduledoc "A comment extracted from source code."

  @typedoc "A comment extracted from source code."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          kind: String.t() | nil,
          span: TreeSitterLanguagePack.Span.t(),
          associated_node: String.t() | nil
        }

  defstruct text: nil,
            kind: :line,
            span: nil,
            associated_node: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
