# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:551f4681b192d2a48b2a1808a8e01ed4b32db9c9e6c69170343ed21fcca4407e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.DiagnosticSeverity do
  @moduledoc """
  Severity level of a diagnostic produced during parsing.

  Used to classify parse errors, warnings, and informational messages
  found in the syntax tree.
  """

  @typedoc "Severity level of a diagnostic produced during parsing."
  @type t :: :error | :warning | :info

  @error :error
  @warning :warning
  @info :info

  @doc "A parse error (e.g., an `ERROR` or `MISSING` node in the tree)."
  @spec error() :: t()
  def error, do: @error
  @doc "A warning-level diagnostic."
  @spec warning() :: t()
  def warning, do: @warning
  @doc "An informational diagnostic."
  @spec info() :: t()
  def info, do: @info
end
