# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bef4da3fe480be6a42d40f41b03f825c709d3d915fc95f69561505c9a474ac43
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.Diagnostic do
  @moduledoc "A diagnostic (syntax error, missing node, etc.) from parsing."

  @typedoc "A diagnostic (syntax error, missing node, etc.) from parsing."
  @type t :: %__MODULE__{
          message: String.t() | nil,
          severity: String.t() | nil,
          span: TreeSitterLanguagePack.Span.t()
        }

  defstruct message: nil,
            severity: :error,
            span: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
