# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:055a988c5051f99c2081a36b9484ba6bbd744d15e747cbfb474a6e2392921d7d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.Diagnostic do
  @moduledoc "A diagnostic (syntax error, missing node, etc.) from parsing."

  @typedoc "A diagnostic (syntax error, missing node, etc.) from parsing."
  @type t :: %__MODULE__{
          message: String.t() | nil,
          severity: String.t() | nil,
          span: TreeSitterLanguagePack.Span.t()
        }

  defstruct message: nil,
            severity: :error,
            span: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
