# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:68c1122c5e9d4625ff17b3ac284750a02712852755f684b5b6e201b2b98a2694
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.Diagnostic do
  @moduledoc "A diagnostic (syntax error, missing node, etc.) from parsing."

  @typedoc "A diagnostic (syntax error, missing node, etc.) from parsing."
  @type t :: %__MODULE__{
  message: String.t() | nil,
  severity: String.t() | nil,
  span: TreeSitterLanguagePack.Span.t()
  }

  defstruct message: nil,
  severity: :error,
  span: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
