# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bef4da3fe480be6a42d40f41b03f825c709d3d915fc95f69561505c9a474ac43
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.DocSection do
  @moduledoc "A section within a docstring (e.g., Args, Returns, Raises)."

  @typedoc "A section within a docstring (e.g., Args, Returns, Raises)."
  @type t :: %__MODULE__{
          kind: String.t() | nil,
          name: String.t() | nil,
          description: String.t() | nil
        }

  defstruct kind: nil,
            name: nil,
            description: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
