# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:551f4681b192d2a48b2a1808a8e01ed4b32db9c9e6c69170343ed21fcca4407e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.DocstringInfo do
  @moduledoc "A docstring extracted from source code."

  @typedoc "A docstring extracted from source code."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          format: String.t() | nil,
          span: TreeSitterLanguagePack.Span.t(),
          associated_item: String.t() | nil,
          parsed_sections: [TreeSitterLanguagePack.DocSection.t()]
        }

  defstruct text: nil,
            format: :python_triple_quote,
            span: nil,
            associated_item: nil,
            parsed_sections: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
