# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bef4da3fe480be6a42d40f41b03f825c709d3d915fc95f69561505c9a474ac43
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.DocstringInfo do
  @moduledoc "A docstring extracted from source code."

  @typedoc "A docstring extracted from source code."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          format: String.t() | nil,
          span: TreeSitterLanguagePack.Span.t(),
          associated_item: String.t() | nil,
          parsed_sections: [TreeSitterLanguagePack.DocSection.t()]
        }

  defstruct text: nil,
            format: :python_triple_quote,
            span: nil,
            associated_item: nil,
            parsed_sections: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
