# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:551f4681b192d2a48b2a1808a8e01ed4b32db9c9e6c69170343ed21fcca4407e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.ExportInfo do
  @moduledoc "An export statement extracted from source code."

  @typedoc "An export statement extracted from source code."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          kind: String.t() | nil,
          span: TreeSitterLanguagePack.Span.t()
        }

  defstruct name: nil,
            kind: :named,
            span: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
