# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:14687d1c1d0c2f444a287af8e41bb8e299062b27c46c2720ef9c04d1c12dc6d0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.ExportKind do
  @moduledoc """
  The kind of an export statement found in source code.

  Covers named exports, default exports, and re-exports from other modules.
  """

  @typedoc "The kind of an export statement found in source code."
  @type t :: :named | :default | :re_export

  @named :named
  @default :default
  @re_export :re_export

  @doc "A named export (e.g., `export { foo }`)."
  @spec named() :: t()
  def named, do: @named
  @doc "A default export (e.g., `export default foo`)."
  @spec default() :: t()
  def default, do: @default
  @doc "A re-export from another module (e.g., `export { foo } from 'bar'`)."
  @spec re_export() :: t()
  def re_export, do: @re_export
end
