# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4a5cc0e3da3c742bea14840829b59ce60f050529e919a038e8e48450bf2b3ff0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.ExportInfo do
  @moduledoc "An export statement extracted from source code."

  @typedoc "An export statement extracted from source code."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          kind: String.t() | nil,
          span: TreeSitterLanguagePack.Span.t()
        }

  defstruct name: nil,
            kind: :named,
            span: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
