# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8505e7bc19f044dabf6699b8a8df05b91c316954eca0cf432ff7a4b71f2b02ea
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.FileMetrics do
  @moduledoc "Aggregate metrics for a source file."

  @typedoc "Aggregate metrics for a source file."
  @type t :: %__MODULE__{
  total_lines: non_neg_integer(),
  code_lines: non_neg_integer(),
  comment_lines: non_neg_integer(),
  blank_lines: non_neg_integer(),
  total_bytes: non_neg_integer(),
  node_count: non_neg_integer(),
  error_count: non_neg_integer(),
  max_depth: non_neg_integer()
  }

  defstruct total_lines: 0,
  code_lines: 0,
  comment_lines: 0,
  blank_lines: 0,
  total_bytes: 0,
  node_count: 0,
  error_count: 0,
  max_depth: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
