# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:68c1122c5e9d4625ff17b3ac284750a02712852755f684b5b6e201b2b98a2694
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.ImportInfo do
  @moduledoc "An import statement extracted from source code."

  @typedoc "An import statement extracted from source code."
  @type t :: %__MODULE__{
  source: String.t() | nil,
  items: [String.t()],
  alias: String.t() | nil,
  is_wildcard: boolean(),
  span: TreeSitterLanguagePack.Span.t()
  }

  defstruct source: nil,
  items: [],
  alias: nil,
  is_wildcard: false,
  span: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
