# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bef4da3fe480be6a42d40f41b03f825c709d3d915fc95f69561505c9a474ac43
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.Language do
  @moduledoc false

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}
end
