# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e0daa4aa08c0f8ff366b6c0739dbb2c201a286cd58fb7cf0091fcc130801eb96
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.Language do
  @moduledoc false

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}
end
