# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:976e3b6b83d187cee6bb9dd6b0b8644f15198c5e45d5a66a3b2d2f7573374a9d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.Language do
  @moduledoc false

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}
end
