# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c4755e5e223f2023d4c34684c2117011d276309e44950a0bd474f1f25564f695
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.Point do
  @moduledoc "A source position — row + column, zero-indexed."

  @typedoc "A source position — row + column, zero-indexed."
  @type t :: %__MODULE__{
          row: non_neg_integer(),
          column: non_neg_integer()
        }

  defstruct row: 0,
            column: 0
end
