# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:06b7e9837480f9546074f03a8ab51fc33c076fb21172ba97a5ab4acce8043a13
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.Point do
  @moduledoc "A source position — row + column, zero-indexed."

  @typedoc "A source position — row + column, zero-indexed."
  @type t :: %__MODULE__{
          row: non_neg_integer(),
          column: non_neg_integer()
        }

  defstruct row: 0,
            column: 0
end
