# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0c16dbdb47e45906c1e1912c47be7581db532ed827bc91ef8f21558496d65c6b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.ProcessConfig do
  @moduledoc """
  Configuration for the `process()` function.

  Controls which analysis features are enabled and whether chunking is performed.

  # Examples

  ```
  use tree_sitter_language_pack::ProcessConfig;

  // Defaults: structure + imports + exports enabled
  let config = ProcessConfig::new("python");

  // With chunking
  let config = ProcessConfig::new("python").with_chunking(1000);

  // Everything enabled
  let config = ProcessConfig::new("python").all();
  ```
  """

  @typedoc "Configuration for the `process()` function."
  @type t :: %__MODULE__{
          language: String.t() | nil,
          structure: boolean(),
          imports: boolean(),
          exports: boolean(),
          comments: boolean(),
          docstrings: boolean(),
          symbols: boolean(),
          diagnostics: boolean(),
          chunk_max_size: non_neg_integer() | nil,
          data_extraction: boolean()
        }

  defstruct language: nil,
            structure: true,
            imports: true,
            exports: true,
            comments: false,
            docstrings: false,
            symbols: false,
            diagnostics: false,
            chunk_max_size: nil,
            data_extraction: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
