# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e25df9c3f55836aaee44f0050cd46a203360ab14910330794ff3cc5ab9ae08c7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.StructureItem do
  @moduledoc "A structural item (function, class, struct, etc.) in source code."

  @typedoc "A structural item (function, class, struct, etc.) in source code."
  @type t :: %__MODULE__{
  kind: String.t() | nil,
  name: String.t() | nil,
  visibility: String.t() | nil,
  span: TreeSitterLanguagePack.Span.t(),
  children: [TreeSitterLanguagePack.StructureItem.t()],
  decorators: [String.t()],
  doc_comment: String.t() | nil,
  signature: String.t() | nil,
  body_span: TreeSitterLanguagePack.Span.t() | nil
  }

  defstruct kind: :function,
  name: nil,
  visibility: nil,
  span: nil,
  children: [],
  decorators: [],
  doc_comment: nil,
  signature: nil,
  body_span: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
