# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:551f4681b192d2a48b2a1808a8e01ed4b32db9c9e6c69170343ed21fcca4407e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.SymbolKind do
  @moduledoc """
  The kind of a symbol definition found in source code.

  Categorizes symbol definitions such as variables, constants, functions,
  classes, types, interfaces, enums, and modules.

  # Wire format (public JSON contract)

  Unit variants serialize as a bare string (`"Function"`); the `Other`
  variant serializes as a single-keyed object (`{"Other": "macro"}`). DO
  NOT add `#[serde(tag = "...")]`. Covered by `tests/wire_format.rs`.
  """

  @typedoc "The kind of a symbol definition found in source code."
  @type t :: term()

  @typedoc "A variable binding."
  @type variable :: :variable
  @typedoc "A constant (immutable binding)."
  @type constant :: :constant
  @typedoc "A function definition."
  @type function_variant :: :function
  @typedoc "A class definition."
  @type class :: :class
  @typedoc "A type alias or typedef."
  @type type :: :type
  @typedoc "An interface definition."
  @type interface :: :interface
  @typedoc "An enum definition."
  @type enum :: :enum
  @typedoc "A module declaration."
  @type module_variant :: :module
  @typedoc "A symbol kind not covered by the standard variants."
  @type other :: %{type: :other, value: String.t()}
end
