# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:68c1122c5e9d4625ff17b3ac284750a02712852755f684b5b6e201b2b98a2694
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.SymbolInfo do
  @moduledoc "A symbol (variable, function, type, etc.) extracted from source code."

  @typedoc "A symbol (variable, function, type, etc.) extracted from source code."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  kind: String.t() | nil,
  span: TreeSitterLanguagePack.Span.t(),
  type_annotation: String.t() | nil,
  doc: String.t() | nil
  }

  defstruct name: nil,
  kind: :variable,
  span: nil,
  type_annotation: nil,
  doc: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
