# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2a01fe5c1adeeb3128de597cad50ddc207142598c86ec71c12a96f3520feba3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.Tree do
  @moduledoc "A parsed syntax tree. Cheap to clone (refcount bump)."

  alias TreeSitterLanguagePack.Native
  defstruct [:ref]

  @typedoc "A parsed syntax tree. Cheap to clone (refcount bump)."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Return the root [`Node`] of this tree."
  def root_node(obj) do
    Native.tree_root_node(obj.ref)
  end

  @doc "Return a [`TreeCursor`] positioned at the root."
  def walk(obj) do
    Native.tree_walk(obj.ref)
  end
end
