# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:06b7e9837480f9546074f03a8ab51fc33c076fb21172ba97a5ab4acce8043a13
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.Tree do
  @moduledoc "A parsed syntax tree. Cheap to clone (refcount bump)."

  alias TreeSitterLanguagePack.Native
  defstruct [:ref]

  @typedoc "A parsed syntax tree. Cheap to clone (refcount bump)."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Return the root [`Node`] of this tree."
  def root_node(obj) do
    Native.tree_root_node(obj.ref)
  end

  @doc "Return a [`TreeCursor`] positioned at the root."
  def walk(obj) do
    Native.tree_walk(obj.ref)
  end
end
