# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c4755e5e223f2023d4c34684c2117011d276309e44950a0bd474f1f25564f695
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.Tree do
  @moduledoc "A parsed syntax tree. Cheap to clone (refcount bump)."

  alias TreeSitterLanguagePack.Native
  defstruct [:ref]

  @typedoc "A parsed syntax tree. Cheap to clone (refcount bump)."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Return the root [`Node`] of this tree."
  def root_node(obj) do
    Native.tree_root_node(obj.ref)
  end

  @doc "Return a [`TreeCursor`] positioned at the root."
  def walk(obj) do
    Native.tree_walk(obj.ref)
  end
end
