// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f8410c49a2a8cd2e0e92374810fae4d9424c737d02781ff263f342df8cb0a87d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 60000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
  },
});
