<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:06b7e9837480f9546074f03a8ab51fc33c076fb21172ba97a5ab4acce8043a13
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Tree\Sitter\Language\Pack;

final class Language
{
}
