<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0c16dbdb47e45906c1e1912c47be7581db532ed827bc91ef8f21558496d65c6b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Tree\Sitter\Language\Pack;

final class Language
{
}
