<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:976e3b6b83d187cee6bb9dd6b0b8644f15198c5e45d5a66a3b2d2f7573374a9d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Tree\Sitter\Language\Pack;

/**
 * A parsed syntax tree. Cheap to clone (refcount bump).
 */
final class Tree
{
    /**
     * Return the root `Node` of this tree.
     */
    public function rootNode(): Node
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * Return a `TreeCursor` positioned at the root.
     */
    public function walk(): TreeCursor
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
