// Generated by alef. Do not edit by hand.
// alef:hash:fa25725a6cbadfc12d71766f7c83702ecf6837346d63834ccccc550e3359b9bd

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "tree-sitter-language-pack-android-e2e"
