packages:
  - "."
  - "crates/ts-pack-core-node"
  - "e2e/node"
onlyBuiltDependencies:
  - esbuild
  - tree-sitter
allowBuilds:
  esbuild: true
  tree-sitter: true
minimumReleaseAgeExclude:
  # pnpm 11+ matches these as name-only globs (the `pkg@version` form is not
  - "@xberg-io/tree-sitter-language-pack-*"

sharedWorkspaceLockfile: true
autoInstallPeers: true
hoist: true
