# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0b3e2088d99291afcbfd3389e3471ccf33579c9480061b0ca3aa5e8db085dd92
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require "json"
require "sorbet-runtime"
require "ts_pack_core_rb"
