# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fa25725a6cbadfc12d71766f7c83702ecf6837346d63834ccccc550e3359b9bd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module TreeSitterLanguagePack
  ## The version string for this package.
  VERSION = "1.13.7"
end
