# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c4755e5e223f2023d4c34684c2117011d276309e44950a0bd474f1f25564f695
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module TreeSitterLanguagePack
  ## The version string for this package.
  VERSION = "1.13.4"
end
