# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:551f4681b192d2a48b2a1808a8e01ed4b32db9c9e6c69170343ed21fcca4407e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module TreeSitterLanguagePack
  ## The version string for this package.
  VERSION = "1.14.3"
end
