# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:06b7e9837480f9546074f03a8ab51fc33c076fb21172ba97a5ab4acce8043a13
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Exception hierarchy (re-exported from the native module)."""

from ._native import (
    CacheLockError,
    ChecksumMismatchError,
    ConfigError,
    DownloadError,
    DynamicLoadError,
    Error,
    InvalidRangeError,
    LanguageNotFoundError,
    LockPoisonedError,
    NullLanguagePointerError,
    ParseFailedError,
    ParserSetupError,
    QueryError,
)

__all__ = [
    "CacheLockError",
    "ChecksumMismatchError",
    "ConfigError",
    "DownloadError",
    "DynamicLoadError",
    "Error",
    "InvalidRangeError",
    "LanguageNotFoundError",
    "LockPoisonedError",
    "NullLanguagePointerError",
    "ParseFailedError",
    "ParserSetupError",
    "QueryError",
]

# Re-point each exception's __module__ at the public package so tracebacks show the
# public name (e.g. "DownloadError"), not the native module name (GitHub issue #147).
_public_module = __name__.rsplit(".", 1)[0]
for _name in __all__:
    globals()[_name].__module__ = _public_module
del _name, _public_module
