// Generated by alef. Do not edit by hand.
// alef:hash:2a01fe5c1adeeb3128de597cad50ddc207142598c86ec71c12a96f3520feba3f
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.tslp.android

/** A chunk of source code with rich metadata. */
data class CodeChunk(
    /** The raw source text of this chunk. */
    val content: String = "",
    /** Inclusive start byte offset of this chunk in the original source. */
    val startByte: Long = 0L,
    /** Exclusive end byte offset of this chunk in the original source. */
    val endByte: Long = 0L,
    /** Zero-indexed start line of this chunk. */
    val startLine: Long = 0L,
    /** Zero-indexed end line of this chunk. */
    val endLine: Long = 0L,
    /** Contextual metadata about this chunk. */
    val metadata: ChunkContext = ChunkContext(),
)
