// Generated by alef. Do not edit by hand.
// alef:hash:976e3b6b83d187cee6bb9dd6b0b8644f15198c5e45d5a66a3b2d2f7573374a9d
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.tslp.android

/**
 * An XML-style attribute attached to an `Element` node.
 *
 * Populated only for `DataNodeKind.Element`; always empty for `KeyValue` and
 * `Sequence` nodes.
 */
data class DataAttribute(
    /** Attribute name (e.g. `"class"`, `"href"`). */
    val name: String = "",
    /** Attribute value as a raw string (quotes stripped). */
    val value: String = "",
    /** Source span covering the entire `name="value"` attribute token. */
    val span: Span = Span(),
)
