// Generated by alef. Do not edit by hand.
// alef:hash:14687d1c1d0c2f444a287af8e41bb8e299062b27c46c2720ef9c04d1c12dc6d0
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.tslp.android

/** A docstring extracted from source code. */
data class DocstringInfo(
    /** The raw text of the docstring. */
    val text: String = "",
    /** The docstring format (Python, JSDoc, Rustdoc, etc.). */
    val format: DocstringFormat,
    /** Source span covering the docstring. */
    val span: Span = Span(),
    /** Name of the item this docstring documents. */
    val associatedItem: String? = null,
    /** Parsed sections of the docstring (Args, Returns, Raises, etc.). */
    val parsedSections: List<DocSection> = emptyList(),
)
