// Generated by alef. Do not edit by hand.
// alef:hash:976e3b6b83d187cee6bb9dd6b0b8644f15198c5e45d5a66a3b2d2f7573374a9d
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.tslp.android

/** An import statement extracted from source code. */
data class ImportInfo(
    /** The module or path being imported from. */
    val source: String = "",
    /** Specific names imported from the source module. */
    val items: List<String> = emptyList(),
    /** Alias assigned to the import (e.g., `import numpy as np`). */
    val alias: String? = null,
    /** Whether this is a wildcard import (e.g., `import *` or `use foo.*`). */
    val isWildcard: Boolean = false,
    /** Source span covering the import statement. */
    val span: Span = Span(),
)
