// Generated by alef. Do not edit by hand.
// alef:hash:e25df9c3f55836aaee44f0050cd46a203360ab14910330794ff3cc5ab9ae08c7
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.tslp.android

/**
 * Configuration for the tree-sitter language pack.
 *
 * Controls cache directory and which languages to pre-download.
 * Can be loaded from a TOML file, constructed programmatically,
 * or passed as a dict/object from language bindings.
 */
data class PackConfig(
    /**
     * Override default cache directory.
     *
     * Default: `~/.cache/tree-sitter-language-pack/v{version}/libs/`
     */
    val cacheDir: String? = null,
    /**
     * Languages to pre-download on init.
     *
     * Each entry is a language name (e.g. `"python"`, `"rust"`).
     */
    val languages: List<String>? = null,
    /** Language groups to pre-download (e.g. `"web"`, `"systems"`, `"scripting"`). */
    val groups: List<String>? = null,
)
