// Generated by alef. Do not edit by hand.
// alef:hash:4a5cc0e3da3c742bea14840829b59ce60f050529e919a038e8e48450bf2b3ff0

package io.xberg.tslp.android

class TreeSitterLanguagePackBridgeException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
