// Generated by alef. Do not edit by hand.
// alef:hash:0b3e2088d99291afcbfd3389e3471ccf33579c9480061b0ca3aa5e8db085dd92

package io.xberg.tslp.android

class TreeSitterLanguagePackBridgeException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
