// Generated by alef. Do not edit by hand.
// alef:hash:14687d1c1d0c2f444a287af8e41bb8e299062b27c46c2720ef9c04d1c12dc6d0

package io.xberg.tslp.android

class TreeSitterLanguagePackBridgeException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
