// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e25df9c3f55836aaee44f0050cd46a203360ab14910330794ff3cc5ab9ae08c7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 60000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
  },
});
