// DO NOT EDIT - auto-generated by alef
// alef:hash:4a5cc0e3da3c742bea14840829b59ce60f050529e919a038e8e48450bf2b3ff0
package io.xberg.treesitterlanguagepack;

/**
 * The cross-process download cache lock file could not be acquired or created.
 */
public class CacheLockException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CacheLockException with the given message. */
  public CacheLockException(final String message) {
    super(message);
  }

  /** Creates a new CacheLockException with the given message and cause. */
  public CacheLockException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
