// DO NOT EDIT - auto-generated by alef
// alef:hash:e0daa4aa08c0f8ff366b6c0739dbb2c201a286cd58fb7cf0091fcc130801eb96
package io.xberg.treesitterlanguagepack;

/**
 * The cross-process download cache lock file could not be acquired or created.
 */
public class CacheLockException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CacheLockException with the given message. */
  public CacheLockException(final String message) {
    super(message);
  }

  /** Creates a new CacheLockException with the given message and cause. */
  public CacheLockException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
