// DO NOT EDIT - auto-generated by alef
// alef:hash:fa25725a6cbadfc12d71766f7c83702ecf6837346d63834ccccc550e3359b9bd
package io.xberg.treesitterlanguagepack;

/**
 * The downloaded file's SHA-256 digest did not match the manifest's expected value.
 */
public class ChecksumMismatchException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ChecksumMismatchException with the given message. */
  public ChecksumMismatchException(final String message) {
    super(message);
  }

  /** Creates a new ChecksumMismatchException with the given message and cause. */
  public ChecksumMismatchException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
