// DO NOT EDIT - auto-generated by alef
// alef:hash:055a988c5051f99c2081a36b9484ba6bbd744d15e747cbfb474a6e2392921d7d
package io.xberg.treesitterlanguagepack;

/**
 * The downloaded file's SHA-256 digest did not match the manifest's expected value.
 */
public class ChecksumMismatchException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ChecksumMismatchException with the given message. */
  public ChecksumMismatchException(final String message) {
    super(message);
  }

  /** Creates a new ChecksumMismatchException with the given message and cause. */
  public ChecksumMismatchException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
