// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:551f4681b192d2a48b2a1808a8e01ed4b32db9c9e6c69170343ed21fcca4407e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The kind of a comment found in source code.
 *
 * Distinguishes between single-line comments, block (multi-line) comments,
 * and documentation comments.
 */
@SuppressWarnings("PMD")
public enum CommentKind {
    /**
     * A single-line comment (e.g., {@code // ...} or {@code # ...}).
     */
    Line("line"),
    /**
     * A block or multi-line comment using slash-star delimiters.
     */
    Block("block"),
    /**
     * A documentation comment such as {@code /// ...} or slash-double-star block.
     */
    Doc("doc");


    /** The string value. */
    private final String value;

    CommentKind(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static CommentKind fromValue(final String value) {
        for (CommentKind e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown CommentKind value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
