// DO NOT EDIT - auto-generated by alef
// alef:hash:fa25725a6cbadfc12d71766f7c83702ecf6837346d63834ccccc550e3359b9bd
package io.xberg.treesitterlanguagepack;

/**
 * A configuration file or value was invalid or could not be applied.
 */
public class ConfigException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConfigException with the given message. */
  public ConfigException(final String message) {
    super(message);
  }

  /** Creates a new ConfigException with the given message and cause. */
  public ConfigException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
