// DO NOT EDIT - auto-generated by alef
// alef:hash:4a5cc0e3da3c742bea14840829b59ce60f050529e919a038e8e48450bf2b3ff0
package io.xberg.treesitterlanguagepack;

/**
 * A configuration file or value was invalid or could not be applied.
 */
public class ConfigException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConfigException with the given message. */
  public ConfigException(final String message) {
    super(message);
  }

  /** Creates a new ConfigException with the given message and cause. */
  public ConfigException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
