// DO NOT EDIT - auto-generated by alef
// alef:hash:551f4681b192d2a48b2a1808a8e01ed4b32db9c9e6c69170343ed21fcca4407e
package io.xberg.treesitterlanguagepack;

/**
 * A configuration file or value was invalid or could not be applied.
 */
public class ConfigException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConfigException with the given message. */
  public ConfigException(final String message) {
    super(message);
  }

  /** Creates a new ConfigException with the given message and cause. */
  public ConfigException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
