// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8505e7bc19f044dabf6699b8a8df05b91c316954eca0cf432ff7a4b71f2b02ea
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.treesitterlanguagepack;

/** Exception thrown when type conversion fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class ConversionErrorException extends TreeSitterLanguagePackRsException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ConversionErrorException. */
    public ConversionErrorException(final String message) {
        super(2, message);
    }

    /** Creates a new ConversionErrorException with a cause. */
    public ConversionErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
