// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2a51c237e4cadecf2724474532807987d8c1e0c7803092ed53d977454ca32775
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Severity level of a diagnostic produced during parsing.
 *
 * Used to classify parse errors, warnings, and informational messages
 * found in the syntax tree.
 */
@SuppressWarnings("PMD")
public enum DiagnosticSeverity {
    /**
     * A parse error (e.g., an {@code ERROR} or {@code MISSING} node in the tree).
     */
    Error("error"),
    /**
     * A warning-level diagnostic.
     */
    Warning("warning"),
    /**
     * An informational diagnostic.
     */
    Info("info");


    /** The string value. */
    private final String value;

    DiagnosticSeverity(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static DiagnosticSeverity fromValue(final String value) {
        for (DiagnosticSeverity e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown DiagnosticSeverity value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
