// DO NOT EDIT - auto-generated by alef
// alef:hash:bef4da3fe480be6a42d40f41b03f825c709d3d915fc95f69561505c9a474ac43
package io.xberg.treesitterlanguagepack;

/**
 * A parser download from GitHub releases failed.
 */
public class DownloadException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DownloadException with the given message. */
  public DownloadException(final String message) {
    super(message);
  }

  /** Creates a new DownloadException with the given message and cause. */
  public DownloadException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
