// DO NOT EDIT - auto-generated by alef
// alef:hash:14687d1c1d0c2f444a287af8e41bb8e299062b27c46c2720ef9c04d1c12dc6d0
package io.xberg.treesitterlanguagepack;

/**
 * A dynamic shared library could not be loaded at runtime.
 */
public class DynamicLoadException extends ErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new DynamicLoadException with the given message. */
    public DynamicLoadException(final String message) {
        super(message);
    }

    /** Creates a new DynamicLoadException with the given message and cause. */
    public DynamicLoadException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
