// DO NOT EDIT - auto-generated by alef
// alef:hash:8505e7bc19f044dabf6699b8a8df05b91c316954eca0cf432ff7a4b71f2b02ea
package io.xberg.treesitterlanguagepack;

/**
 * A dynamic shared library could not be loaded at runtime.
 */
public class DynamicLoadException extends ErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new DynamicLoadException with the given message. */
    public DynamicLoadException(final String message) {
        super(message);
    }

    /** Creates a new DynamicLoadException with the given message and cause. */
    public DynamicLoadException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
