// DO NOT EDIT - auto-generated by alef
// alef:hash:2a51c237e4cadecf2724474532807987d8c1e0c7803092ed53d977454ca32775
package io.xberg.treesitterlanguagepack;

/**
 * A dynamic shared library could not be loaded at runtime.
 */
public class DynamicLoadException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DynamicLoadException with the given message. */
  public DynamicLoadException(final String message) {
    super(message);
  }

  /** Creates a new DynamicLoadException with the given message and cause. */
  public DynamicLoadException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
