// DO NOT EDIT - auto-generated by alef
// alef:hash:bef4da3fe480be6a42d40f41b03f825c709d3d915fc95f69561505c9a474ac43
package io.xberg.treesitterlanguagepack;

/**
 * Errors that can occur when using the tree-sitter language pack.
 *
 * Covers language lookup failures, parse errors, query errors, and I/O issues.
 * Feature-gated variants are included when `config`, `download`, or related
 * features are enabled.
 */
public class ErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new ErrorException with the given message. */
  public ErrorException(final String message) {
    super(message);
  }

  /** Creates a new ErrorException with the given message and cause. */
  public ErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
