// DO NOT EDIT - auto-generated by alef
// alef:hash:2a01fe5c1adeeb3128de597cad50ddc207142598c86ec71c12a96f3520feba3f
package io.xberg.treesitterlanguagepack;

/**
 * Errors that can occur when using the tree-sitter language pack.
 *
 * Covers language lookup failures, parse errors, query errors, and I/O issues.
 * Feature-gated variants are included when `config`, `download`, or related
 * features are enabled.
 */
public class ErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new ErrorException with the given message. */
  public ErrorException(final String message) {
    super(message);
  }

  /** Creates a new ErrorException with the given message and cause. */
  public ErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
