// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bef4da3fe480be6a42d40f41b03f825c709d3d915fc95f69561505c9a474ac43
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The kind of an export statement found in source code.
 *
 * Covers named exports, default exports, and re-exports from other modules.
 */
@SuppressWarnings("PMD")
public enum ExportKind {
    /**
     * A named export (e.g., {@code export { foo }}).
     */
    Named("named"),
    /**
     * A default export (e.g., {@code export default foo}).
     */
    Default("default"),
    /**
     * A re-export from another module (e.g., {@code export { foo } from 'bar'}).
     */
    ReExport("reexport");


    /** The string value. */
    private final String value;

    ExportKind(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ExportKind fromValue(final String value) {
        for (ExportKind e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown ExportKind value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
