// DO NOT EDIT - auto-generated by alef
// alef:hash:9c8bcc173caa41eb8dcf14ba50cbc3a20a980281fe51c5b4ec53a5f2a79bab50
package io.xberg.treesitterlanguagepack;

/**
 * A byte range was invalid (e.g., end before start, or out of bounds).
 */
public class InvalidRangeException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidRangeException with the given message. */
  public InvalidRangeException(final String message) {
    super(message);
  }

  /** Creates a new InvalidRangeException with the given message and cause. */
  public InvalidRangeException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
