// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e0daa4aa08c0f8ff366b6c0739dbb2c201a286cd58fb7cf0091fcc130801eb96
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.treesitterlanguagepack;

/** Exception thrown when input validation fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class InvalidInputException extends TreeSitterLanguagePackRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidInputException. */
  public InvalidInputException(final String message) {
    super(1, message);
  }

  /** Creates a new InvalidInputException with a cause. */
  public InvalidInputException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
