// DO NOT EDIT - auto-generated by alef
// alef:hash:a023f35f8248a79aed5fb81fb746e8a495ec5dc144ed925957c15f8b8ca7ec0a
package io.xberg.treesitterlanguagepack;

/**
 * A byte range was invalid (e.g., end before start, or out of bounds).
 */
public class InvalidRangeException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidRangeException with the given message. */
  public InvalidRangeException(final String message) {
    super(message);
  }

  /** Creates a new InvalidRangeException with the given message and cause. */
  public InvalidRangeException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
