// DO NOT EDIT - auto-generated by alef
// alef:hash:0b3e2088d99291afcbfd3389e3471ccf33579c9480061b0ca3aa5e8db085dd92
package io.xberg.treesitterlanguagepack;

/**
 * The requested language name (or alias) was not found in the registry.
 */
public class LanguageNotFoundException extends ErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new LanguageNotFoundException with the given message. */
    public LanguageNotFoundException(final String message) {
        super(message);
    }

    /** Creates a new LanguageNotFoundException with the given message and cause. */
    public LanguageNotFoundException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
