// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e25df9c3f55836aaee44f0050cd46a203360ab14910330794ff3cc5ab9ae08c7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.treesitterlanguagepack;

import java.lang.foreign.MemorySegment;

@SuppressWarnings("PMD")
public class Language implements AutoCloseable {
    private final MemorySegment handle;

    Language(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }
    @Override
    @SuppressWarnings("PMD.AvoidCatchingGenericException")
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.TS_PACK_LANGUAGE_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free Language: " + e.getMessage(), e);
            }
        }
    }
}
