// DO NOT EDIT - auto-generated by alef
// alef:hash:551f4681b192d2a48b2a1808a8e01ed4b32db9c9e6c69170343ed21fcca4407e
package io.xberg.treesitterlanguagepack;

/**
 * The requested language name (or alias) was not found in the registry.
 */
public class LanguageNotFoundException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new LanguageNotFoundException with the given message. */
  public LanguageNotFoundException(final String message) {
    super(message);
  }

  /** Creates a new LanguageNotFoundException with the given message and cause. */
  public LanguageNotFoundException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
