// DO NOT EDIT - auto-generated by alef
// alef:hash:e6a18c461da2c31bd3854d90a068c14c4ffb67f3a73f23fe765dad50d70c4266
package io.xberg.treesitterlanguagepack;

/**
 * An internal `RwLock` or `Mutex` was poisoned by a previous panic.
 */
public class LockPoisonedException extends ErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
