// DO NOT EDIT - auto-generated by alef
// alef:hash:2a01fe5c1adeeb3128de597cad50ddc207142598c86ec71c12a96f3520feba3f
package io.xberg.treesitterlanguagepack;

/**
 * An internal `RwLock` or `Mutex` was poisoned by a previous panic.
 */
public class LockPoisonedException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new LockPoisonedException with the given message. */
  public LockPoisonedException(final String message) {
    super(message);
  }

  /** Creates a new LockPoisonedException with the given message and cause. */
  public LockPoisonedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
