// DO NOT EDIT - auto-generated by alef
// alef:hash:06b7e9837480f9546074f03a8ab51fc33c076fb21172ba97a5ab4acce8043a13
package io.xberg.treesitterlanguagepack;

/**
 * An internal `RwLock` or `Mutex` was poisoned by a previous panic.
 */
public class LockPoisonedException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new LockPoisonedException with the given message. */
  public LockPoisonedException(final String message) {
    super(message);
  }

  /** Creates a new LockPoisonedException with the given message and cause. */
  public LockPoisonedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
