// DO NOT EDIT - auto-generated by alef
// alef:hash:976e3b6b83d187cee6bb9dd6b0b8644f15198c5e45d5a66a3b2d2f7573374a9d
package io.xberg.treesitterlanguagepack;

/**
 * The tree-sitter language function returned a null pointer for the given language name.
 */
public class NullLanguagePointerException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new NullLanguagePointerException with the given message. */
  public NullLanguagePointerException(final String message) {
    super(message);
  }

  /** Creates a new NullLanguagePointerException with the given message and cause. */
  public NullLanguagePointerException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
