// DO NOT EDIT - auto-generated by alef
// alef:hash:4a5cc0e3da3c742bea14840829b59ce60f050529e919a038e8e48450bf2b3ff0
package io.xberg.treesitterlanguagepack;

/**
 * The tree-sitter language function returned a null pointer for the given language name.
 */
public class NullLanguagePointerException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new NullLanguagePointerException with the given message. */
  public NullLanguagePointerException(final String message) {
    super(message);
  }

  /** Creates a new NullLanguagePointerException with the given message and cause. */
  public NullLanguagePointerException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
