// DO NOT EDIT - auto-generated by alef
// alef:hash:9c8bcc173caa41eb8dcf14ba50cbc3a20a980281fe51c5b4ec53a5f2a79bab50
package io.xberg.treesitterlanguagepack;

/**
 * The tree-sitter language function returned a null pointer for the given language name.
 */
public class NullLanguagePointerException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new NullLanguagePointerException with the given message. */
  public NullLanguagePointerException(final String message) {
    super(message);
  }

  /** Creates a new NullLanguagePointerException with the given message and cause. */
  public NullLanguagePointerException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
