// DO NOT EDIT - auto-generated by alef
// alef:hash:2a01fe5c1adeeb3128de597cad50ddc207142598c86ec71c12a96f3520feba3f
package io.xberg.treesitterlanguagepack;

/**
 * The tree-sitter parser returned no tree for the given source input.
 */
public class ParseFailedException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParseFailedException with the given message. */
  public ParseFailedException(final String message) {
    super(message);
  }

  /** Creates a new ParseFailedException with the given message and cause. */
  public ParseFailedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
