// DO NOT EDIT - auto-generated by alef
// alef:hash:2a01fe5c1adeeb3128de597cad50ddc207142598c86ec71c12a96f3520feba3f
package io.xberg.treesitterlanguagepack;

/**
 * The language could not be applied to the parser (e.g., ABI version mismatch).
 */
public class ParserSetupException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParserSetupException with the given message. */
  public ParserSetupException(final String message) {
    super(message);
  }

  /** Creates a new ParserSetupException with the given message and cause. */
  public ParserSetupException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
