// DO NOT EDIT - auto-generated by alef
// alef:hash:e0daa4aa08c0f8ff366b6c0739dbb2c201a286cd58fb7cf0091fcc130801eb96
package io.xberg.treesitterlanguagepack;

/**
 * The tree-sitter parser returned no tree for the given source input.
 */
public class ParseFailedException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParseFailedException with the given message. */
  public ParseFailedException(final String message) {
    super(message);
  }

  /** Creates a new ParseFailedException with the given message and cause. */
  public ParseFailedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
