// DO NOT EDIT - auto-generated by alef
// alef:hash:68c1122c5e9d4625ff17b3ac284750a02712852755f684b5b6e201b2b98a2694
package io.xberg.treesitterlanguagepack;

/**
 * The language could not be applied to the parser (e.g., ABI version mismatch).
 */
public class ParserSetupException extends ErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ParserSetupException with the given message. */
    public ParserSetupException(final String message) {
        super(message);
    }

    /** Creates a new ParserSetupException with the given message and cause. */
    public ParserSetupException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
