// DO NOT EDIT - auto-generated by alef
// alef:hash:68c1122c5e9d4625ff17b3ac284750a02712852755f684b5b6e201b2b98a2694
package io.xberg.treesitterlanguagepack;

/**
 * The tree-sitter parser returned no tree for the given source input.
 */
public class ParseFailedException extends ErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ParseFailedException with the given message. */
    public ParseFailedException(final String message) {
        super(message);
    }

    /** Creates a new ParseFailedException with the given message and cause. */
    public ParseFailedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
