// DO NOT EDIT - auto-generated by alef
// alef:hash:a023f35f8248a79aed5fb81fb746e8a495ec5dc144ed925957c15f8b8ca7ec0a
package io.xberg.treesitterlanguagepack;

/**
 * A tree-sitter query could not be compiled or executed.
 */
public class QueryErrorException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new QueryErrorException with the given message. */
  public QueryErrorException(final String message) {
    super(message);
  }

  /** Creates a new QueryErrorException with the given message and cause. */
  public QueryErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
