// DO NOT EDIT - auto-generated by alef
// alef:hash:4a5cc0e3da3c742bea14840829b59ce60f050529e919a038e8e48450bf2b3ff0
package io.xberg.treesitterlanguagepack;

/**
 * A tree-sitter query could not be compiled or executed.
 */
public class QueryErrorException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new QueryErrorException with the given message. */
  public QueryErrorException(final String message) {
    super(message);
  }

  /** Creates a new QueryErrorException with the given message and cause. */
  public QueryErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
