// DO NOT EDIT - auto-generated by alef
// alef:hash:68c1122c5e9d4625ff17b3ac284750a02712852755f684b5b6e201b2b98a2694
package io.xberg.treesitterlanguagepack;

/**
 * A tree-sitter query could not be compiled or executed.
 */
public class QueryErrorException extends ErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new QueryErrorException with the given message. */
    public QueryErrorException(final String message) {
        super(message);
    }

    /** Creates a new QueryErrorException with the given message and cause. */
    public QueryErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
