// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c4755e5e223f2023d4c34684c2117011d276309e44950a0bd474f1f25564f695
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.treesitterlanguagepack;

/** Exception thrown by TreeSitterLanguagePackRs. */
public class TreeSitterLanguagePackRsException extends Exception {
  private static final long serialVersionUID = 1L;
  /** The error code. */
  private final int code;

  /** Creates a new TreeSitterLanguagePackRsException. */
  public TreeSitterLanguagePackRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new TreeSitterLanguagePackRsException with a cause. */
  public TreeSitterLanguagePackRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
