// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bef4da3fe480be6a42d40f41b03f825c709d3d915fc95f69561505c9a474ac43
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.treesitterlanguagepack;

/** Exception thrown by TreeSitterLanguagePackRs. */
public class TreeSitterLanguagePackRsException extends Exception {
  private static final long serialVersionUID = 1L;
  /** The error code. */
  private final int code;

  /** Creates a new TreeSitterLanguagePackRsException. */
  public TreeSitterLanguagePackRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new TreeSitterLanguagePackRsException with a cause. */
  public TreeSitterLanguagePackRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
