// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:551f4681b192d2a48b2a1808a8e01ed4b32db9c9e6c69170343ed21fcca4407e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
const std = @import("std");
const testing = std.testing;
const tree_sitter_language_pack = @import("tree_sitter_language_pack");

// Suppress C++ global destructor aborts that break zig's --listen=- IPC
extern "c" fn signal(sig: i32, handler: usize) usize;
var _abort_handler_installed: bool = false;
fn suppress_abort() void {
    if (!_abort_handler_installed) {
        // SIGABRT = 6 on POSIX; SIG_IGN = 1
        _ = signal(6, 1);
        _abort_handler_installed = true;
    }
}

// E2e tests for category: data_extraction

test "data_extraction_json_array" {
    // Data extraction: JSON top-level array emits Sequence nodes
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("[1, 2, 3]", "{\"data_extraction\":true,\"language\":\"json\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "data_extraction_json_empty_object" {
    // Data extraction: JSON empty object produces zero children
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("{}", "{\"data_extraction\":true,\"language\":\"json\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "data_extraction_json_flat" {
    // Data extraction: JSON flat key-value object
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("{\"host\": \"localhost\", \"port\": 8080}", "{\"data_extraction\":true,\"language\":\"json\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "data_extraction_json_nested" {
    // Data extraction: JSON nested object preserves hierarchy
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("{\"server\": {\"host\": \"x\", \"port\": 8080}}", "{\"data_extraction\":true,\"language\":\"json\"}");
    defer std.heap.c_allocator.free(_result_json);
}
