<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:14687d1c1d0c2f444a287af8e41bb8e299062b27c46c2720ef9c04d1c12dc6d0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Tree\Sitter\Language\Pack;

/**
 * Manages downloading and caching of pre-built parser shared libraries.
 */
final class DownloadManager
{
    /**
     * List languages that are already downloaded and cached.
     * @return array<string>
     */
    public function installedLanguages(): array
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }

    /**
     * Download the platform bundle and extract every library file it contains.
     */
    public function downloadAllBestEffort(): int
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }

    /**
     * Remove all cached parser libraries.
     */
    public function cleanCache(): void {}

    /**
     * Create a new download manager for the given version.
     */
    public static function new(string $version): DownloadManager
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
