<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8505e7bc19f044dabf6699b8a8df05b91c316954eca0cf432ff7a4b71f2b02ea
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Tree\Sitter\Language\Pack;

final class Language {}
