<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:14687d1c1d0c2f444a287af8e41bb8e299062b27c46c2720ef9c04d1c12dc6d0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Tree\Sitter\Language\Pack;

/**
 * A tree-sitter parser configured for one language at a time.
 *
 * # Example
 */
final class Parser
{
    /**
     * Configure the parser to use the language identified by name (e.g. `"python"`).
     */
    public function setLanguage(string $name): void {}

    /**
     * Parse a UTF-8 source string. Returns `None` if parsing was cancelled
     */
    public function parse(string $source): ?Tree
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }

    /**
     * Parse a raw byte slice. Returns `None` if parsing was cancelled or
     */
    public function parseBytes(string $source): ?Tree
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }

    /**
     * Reset internal state. The next call to `parse` will
     */
    public function reset(): void {}

    /**
     * Construct a new parser with no language set.
     */
    public static function new(): Parser
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }

    public static function default(): Parser
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
