<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e25df9c3f55836aaee44f0050cd46a203360ab14910330794ff3cc5ab9ae08c7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Tree\Sitter\Language\Pack;

/**
 * A parsed syntax tree. Cheap to clone (refcount bump).
 */
final class Tree
{
    /**
     * Return the root `Node` of this tree.
     */
    public function rootNode(): Node
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }

    /**
     * Return a `TreeCursor` positioned at the root.
     */
    public function walk(): TreeCursor
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
