// Generated by alef. Imports the full tree_sitter_language_pack API.
// alef:hash:0c16dbdb47e45906c1e1912c47be7581db532ed827bc91ef8f21558496d65c6b
pub const api = @import("tree_sitter_language_pack.zig");
