// Generated by alef. Imports the full tree_sitter_language_pack API.
// alef:hash:2a01fe5c1adeeb3128de597cad50ddc207142598c86ec71c12a96f3520feba3f
pub const api = @import("tree_sitter_language_pack.zig");
