// Generated by alef. Imports the full tree_sitter_language_pack API.
// alef:hash:14687d1c1d0c2f444a287af8e41bb8e299062b27c46c2720ef9c04d1c12dc6d0
pub const api = @import("tree_sitter_language_pack.zig");
