# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f8410c49a2a8cd2e0e92374810fae4d9424c737d02781ff263f342df8cb0a87d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The tree_sitter_language_pack package is expected to be installed in the current environment.
