# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9c8bcc173caa41eb8dcf14ba50cbc3a20a980281fe51c5b4ec53a5f2a79bab50
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "tree_sitter_language_pack/version"
require_relative "tree_sitter_language_pack/native"

# Top-level namespace for the TreeSitterLanguagePack Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "tree_sitter_language_pack/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module TreeSitterLanguagePack
  # Re-export all types and functions from native extension
end

# Keep generated types under TreeSitterLanguagePack. Publishing generated constants
# into Object makes generic names collide with unrelated Ruby libraries.
