# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2a01fe5c1adeeb3128de597cad50ddc207142598c86ec71c12a96f3520feba3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "tree_sitter_language_pack/version"
require_relative "tree_sitter_language_pack/native"

# Top-level namespace for the TreeSitterLanguagePack Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "tree_sitter_language_pack/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module TreeSitterLanguagePack
  # Re-export all types and functions from native extension
end

# Bring top-level TreeSitterLanguagePack classes into the global namespace so callers
# (and the generated e2e suite) can reference them unqualified. The native
# extension has already been required above, so every type constant is defined
# under TreeSitterLanguagePack by this point.
TreeSitterLanguagePack.constants.each do |const_name|
  value = TreeSitterLanguagePack.const_get(const_name)
  ::Object.const_set(const_name, value) if value.is_a?(Module) && !::Object.const_defined?(const_name)
end
