# Generated by alef. Do not edit by hand.
# alef:hash:0c16dbdb47e45906c1e1912c47be7581db532ed827bc91ef8f21558496d65c6b
# Keep generated public API for consumers using R8/ProGuard.
-keep class io.xberg.tslp.android.** { *; }
