# Generated by alef. Do not edit by hand.
# alef:hash:2a01fe5c1adeeb3128de597cad50ddc207142598c86ec71c12a96f3520feba3f
# Keep generated public API for consumers using R8/ProGuard.
-keep class io.xberg.tslp.android.** { *; }
