# Generated by alef. Do not edit by hand.
# alef:hash:9c8bcc173caa41eb8dcf14ba50cbc3a20a980281fe51c5b4ec53a5f2a79bab50
# Keep generated public API for consumers using R8/ProGuard.
-keep class io.xberg.tslp.android.** { *; }
