// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e6a18c461da2c31bd3854d90a068c14c4ffb67f3a73f23fe765dad50d70c4266
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
  },
});
