// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9c8bcc173caa41eb8dcf14ba50cbc3a20a980281fe51c5b4ec53a5f2a79bab50
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
  },
});
