// Generated by alef. Do not edit by hand.
// alef:hash:a023f35f8248a79aed5fb81fb746e8a495ec5dc144ed925957c15f8b8ca7ec0a

// Traits module (empty in Dart as Dart does not have trait systems like Rust).
// This file is kept for API surface consistency across language bindings.
