// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9c8bcc173caa41eb8dcf14ba50cbc3a20a980281fe51c5b4ec53a5f2a79bab50
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The cross-process download cache lock file could not be acquired or created.
/// </summary>
public class CacheLockException : ErrorException
{
    public CacheLockException(string message) : base(message) { }

    public CacheLockException(string message, Exception innerException) : base(message, innerException) { }
}
