// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:055a988c5051f99c2081a36b9484ba6bbd744d15e747cbfb474a6e2392921d7d
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The cross-process download cache lock file could not be acquired or created.
/// </summary>
public class CacheLockException : ErrorException
{
    public CacheLockException(string message) : base(message) { }

    public CacheLockException(string message, Exception innerException) : base(message, innerException) { }
}
