// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:06b7e9837480f9546074f03a8ab51fc33c076fb21172ba97a5ab4acce8043a13
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The downloaded file's SHA-256 digest did not match the manifest's expected value.
/// </summary>
public class ChecksumMismatchException : ErrorException
{
    public ChecksumMismatchException(string message) : base(message) { }

    public ChecksumMismatchException(string message, Exception innerException) : base(message, innerException) { }
}
