// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fa25725a6cbadfc12d71766f7c83702ecf6837346d63834ccccc550e3359b9bd
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The downloaded file's SHA-256 digest did not match the manifest's expected value.
/// </summary>
public class ChecksumMismatchException : ErrorException
{
    public ChecksumMismatchException(string message) : base(message) { }

    public ChecksumMismatchException(string message, Exception innerException) : base(message, innerException) { }
}
