// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:976e3b6b83d187cee6bb9dd6b0b8644f15198c5e45d5a66a3b2d2f7573374a9d
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;
/// <summary>
/// The kind of a comment found in source code.
///
/// Distinguishes between single-line comments, block (multi-line) comments,
/// and documentation comments.
/// </summary>
[JsonConverter(typeof(CommentKindJsonConverter))]
public enum CommentKind
{
    /// <summary>
    /// A single-line comment (e.g., `// ...` or `# ...`).
    /// </summary>
    [JsonPropertyName("Line")]
    Line,
    /// <summary>
    /// A block or multi-line comment using slash-star delimiters.
    /// </summary>
    [JsonPropertyName("Block")]
    Block,
    /// <summary>
    /// A documentation comment such as `/// ...` or slash-double-star block.
    /// </summary>
    [JsonPropertyName("Doc")]
    Doc,
}


/// <summary>
/// Custom JSON converter for <see cref="CommentKind"/> that respects explicit variant names.
/// </summary>
internal sealed class CommentKindJsonConverter : JsonConverter<CommentKind>
{
    public override CommentKind Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "Line" => CommentKind.Line,
            "Block" => CommentKind.Block,
            "Doc" => CommentKind.Doc,
            _ => throw new JsonException($"Unknown CommentKind value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, CommentKind value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            CommentKind.Line => "Line",
            CommentKind.Block => "Block",
            CommentKind.Doc => "Doc",
            _ => throw new JsonException($"Unknown CommentKind value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
