// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e0daa4aa08c0f8ff366b6c0739dbb2c201a286cd58fb7cf0091fcc130801eb96
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A configuration file or value was invalid or could not be applied.
/// </summary>
public class ConfigException : ErrorException
{
    public ConfigException(string message) : base(message) { }

    public ConfigException(string message, Exception innerException) : base(message, innerException) { }
}
