// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:68c1122c5e9d4625ff17b3ac284750a02712852755f684b5b6e201b2b98a2694
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A configuration file or value was invalid or could not be applied.
/// </summary>
public class ConfigException : ErrorException
{
    public ConfigException(string message) : base(message) { }

    public ConfigException(string message, Exception innerException) : base(message, innerException) { }
}
