// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:976e3b6b83d187cee6bb9dd6b0b8644f15198c5e45d5a66a3b2d2f7573374a9d
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;
/// <summary>
/// Severity level of a diagnostic produced during parsing.
///
/// Used to classify parse errors, warnings, and informational messages
/// found in the syntax tree.
/// </summary>
[JsonConverter(typeof(DiagnosticSeverityJsonConverter))]
public enum DiagnosticSeverity
{
    /// <summary>
    /// A parse error (e.g., an `ERROR` or `MISSING` node in the tree).
    /// </summary>
    [JsonPropertyName("Error")]
    Error,
    /// <summary>
    /// A warning-level diagnostic.
    /// </summary>
    [JsonPropertyName("Warning")]
    Warning,
    /// <summary>
    /// An informational diagnostic.
    /// </summary>
    [JsonPropertyName("Info")]
    Info,
}


/// <summary>
/// Custom JSON converter for <see cref="DiagnosticSeverity"/> that respects explicit variant names.
/// </summary>
internal sealed class DiagnosticSeverityJsonConverter : JsonConverter<DiagnosticSeverity>
{
    public override DiagnosticSeverity Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "Error" => DiagnosticSeverity.Error,
            "Warning" => DiagnosticSeverity.Warning,
            "Info" => DiagnosticSeverity.Info,
            _ => throw new JsonException($"Unknown DiagnosticSeverity value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, DiagnosticSeverity value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            DiagnosticSeverity.Error => "Error",
            DiagnosticSeverity.Warning => "Warning",
            DiagnosticSeverity.Info => "Info",
            _ => throw new JsonException($"Unknown DiagnosticSeverity value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
