// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a023f35f8248a79aed5fb81fb746e8a495ec5dc144ed925957c15f8b8ca7ec0a
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A parser download from GitHub releases failed.
/// </summary>
public class DownloadException : ErrorException
{
    public DownloadException(string message) : base(message) { }

    public DownloadException(string message, Exception innerException) : base(message, innerException) { }
}
