// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:055a988c5051f99c2081a36b9484ba6bbd744d15e747cbfb474a6e2392921d7d
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A parser download from GitHub releases failed.
/// </summary>
public class DownloadException : ErrorException
{
    public DownloadException(string message) : base(message) { }

    public DownloadException(string message, Exception innerException) : base(message, innerException) { }
}
