// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9c8bcc173caa41eb8dcf14ba50cbc3a20a980281fe51c5b4ec53a5f2a79bab50
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A dynamic shared library could not be loaded at runtime.
/// </summary>
public class DynamicLoadException : ErrorException
{
    public DynamicLoadException(string message) : base(message) { }

    public DynamicLoadException(string message, Exception innerException) : base(message, innerException) { }
}
