// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:976e3b6b83d187cee6bb9dd6b0b8644f15198c5e45d5a66a3b2d2f7573374a9d
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A dynamic shared library could not be loaded at runtime.
/// </summary>
public class DynamicLoadException : ErrorException
{
    public DynamicLoadException(string message) : base(message) { }

    public DynamicLoadException(string message, Exception innerException) : base(message, innerException) { }
}
