// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4a5cc0e3da3c742bea14840829b59ce60f050529e919a038e8e48450bf2b3ff0
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A dynamic shared library could not be loaded at runtime.
/// </summary>
public class DynamicLoadException : ErrorException
{
    public DynamicLoadException(string message) : base(message) { }

    public DynamicLoadException(string message, Exception innerException) : base(message, innerException) { }
}
