// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c4755e5e223f2023d4c34684c2117011d276309e44950a0bd474f1f25564f695
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// Errors that can occur when using the tree-sitter language pack.
///
/// Covers language lookup failures, parse errors, query errors, and I/O issues.
/// Feature-gated variants are included when `config`, `download`, or related
/// features are enabled.
/// </summary>
public class ErrorException : TreeSitterLanguagePackException
{
    public ErrorException(string message) : base(message) { }

    public ErrorException(string message, Exception innerException) : base(message, innerException) { }
}
