// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:14687d1c1d0c2f444a287af8e41bb8e299062b27c46c2720ef9c04d1c12dc6d0
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// Errors that can occur when using the tree-sitter language pack.
///
/// Covers language lookup failures, parse errors, query errors, and I/O issues.
/// Feature-gated variants are included when `config`, `download`, or related
/// features are enabled.
/// </summary>
public class ErrorException : TreeSitterLanguagePackException
{
    public ErrorException(string message) : base(message) { }

    public ErrorException(string message, Exception innerException) : base(message, innerException) { }
}
