// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:976e3b6b83d187cee6bb9dd6b0b8644f15198c5e45d5a66a3b2d2f7573374a9d
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// Errors that can occur when using the tree-sitter language pack.
///
/// Covers language lookup failures, parse errors, query errors, and I/O issues.
/// Feature-gated variants are included when `config`, `download`, or related
/// features are enabled.
/// </summary>
public class ErrorException : TreeSitterLanguagePackException
{
    public ErrorException(string message) : base(message) { }

    public ErrorException(string message, Exception innerException) : base(message, innerException) { }
}
