// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c4755e5e223f2023d4c34684c2117011d276309e44950a0bd474f1f25564f695
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// An export statement extracted from source code.
/// </summary>
public sealed record ExportInfo
{
    /// <summary>
    /// The exported name.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = "";

    /// <summary>
    /// The kind of export (named, default, or re-export).
    /// </summary>
    [JsonPropertyName("kind")]
    public ExportKind? Kind { get; init; } = null;

    /// <summary>
    /// Source span covering the export statement.
    /// </summary>
    [JsonPropertyName("span")]
    public Span Span { get; init; } = default!;


    /// <summary>
    /// Parse a <see cref="ExportInfo"/> from a JSON string.
    /// </summary>
    /// <exception cref="TreeSitterLanguagePackException">When the JSON cannot be deserialised.</exception>
    public static ExportInfo FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ExportInfo>(json, JsonOptions)
                ?? throw new TreeSitterLanguagePackException($"Failed to parse ExportInfo from JSON: deserializer returned null");
        }
        catch (TreeSitterLanguagePackException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new TreeSitterLanguagePackException($"Failed to parse ExportInfo from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
