// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:68c1122c5e9d4625ff17b3ac284750a02712852755f684b5b6e201b2b98a2694
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A byte range was invalid (e.g., end before start, or out of bounds).
/// </summary>
public class InvalidRangeException : ErrorException
{
    public InvalidRangeException(string message) : base(message) { }

    public InvalidRangeException(string message, Exception innerException) : base(message, innerException) { }
}
