// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:976e3b6b83d187cee6bb9dd6b0b8644f15198c5e45d5a66a3b2d2f7573374a9d
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A byte range was invalid (e.g., end before start, or out of bounds).
/// </summary>
public class InvalidRangeException : ErrorException
{
    public InvalidRangeException(string message) : base(message) { }

    public InvalidRangeException(string message, Exception innerException) : base(message, innerException) { }
}
