// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2a51c237e4cadecf2724474532807987d8c1e0c7803092ed53d977454ca32775
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;

namespace TreeSitterLanguagePack;

internal sealed class LanguageSafeHandle : SafeHandle
{
    internal LanguageSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.LanguageFree(handle);
        return true;
    }
}

public sealed class Language : IDisposable
{
    private readonly LanguageSafeHandle _safeHandle;

    internal Language(IntPtr handle)
    {
        _safeHandle = new LanguageSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();

}
