// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e0daa4aa08c0f8ff366b6c0739dbb2c201a286cd58fb7cf0091fcc130801eb96
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;

namespace TreeSitterLanguagePack;

internal sealed class LanguageSafeHandle : SafeHandle
{
    internal LanguageSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.LanguageFree(handle);
        return true;
    }
}

public sealed class Language : IDisposable
{
    private readonly LanguageSafeHandle _safeHandle;

    internal Language(IntPtr handle)
    {
        _safeHandle = new LanguageSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();

}
