// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e25df9c3f55836aaee44f0050cd46a203360ab14910330794ff3cc5ab9ae08c7
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The requested language name (or alias) was not found in the registry.
/// </summary>
public class LanguageNotFoundException : ErrorException
{
    public LanguageNotFoundException(string message) : base(message) { }

    public LanguageNotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
