// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9c8bcc173caa41eb8dcf14ba50cbc3a20a980281fe51c5b4ec53a5f2a79bab50
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// An internal `RwLock` or `Mutex` was poisoned by a previous panic.
/// </summary>
public class LockPoisonedException : ErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
