// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4a5cc0e3da3c742bea14840829b59ce60f050529e919a038e8e48450bf2b3ff0
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// An internal `RwLock` or `Mutex` was poisoned by a previous panic.
/// </summary>
public class LockPoisonedException : ErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
