// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:bef4da3fe480be6a42d40f41b03f825c709d3d915fc95f69561505c9a474ac43
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The tree-sitter language function returned a null pointer for the given language name.
/// </summary>
public class NullLanguagePointerException : ErrorException
{
    public NullLanguagePointerException(string message) : base(message) { }

    public NullLanguagePointerException(string message, Exception innerException) : base(message, innerException) { }
}
