// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2a01fe5c1adeeb3128de597cad50ddc207142598c86ec71c12a96f3520feba3f
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The tree-sitter language function returned a null pointer for the given language name.
/// </summary>
public class NullLanguagePointerException : ErrorException
{
    public NullLanguagePointerException(string message) : base(message) { }

    public NullLanguagePointerException(string message, Exception innerException) : base(message, innerException) { }
}
