// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0b3e2088d99291afcbfd3389e3471ccf33579c9480061b0ca3aa5e8db085dd92
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The tree-sitter language function returned a null pointer for the given language name.
/// </summary>
public class NullLanguagePointerException : ErrorException
{
    public NullLanguagePointerException(string message) : base(message) { }

    public NullLanguagePointerException(string message, Exception innerException) : base(message, innerException) { }
}
