// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:551f4681b192d2a48b2a1808a8e01ed4b32db9c9e6c69170343ed21fcca4407e
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The language could not be applied to the parser (e.g., ABI version mismatch).
/// </summary>
public class ParserSetupException : ErrorException
{
    public ParserSetupException(string message) : base(message) { }

    public ParserSetupException(string message, Exception innerException) : base(message, innerException) { }
}
