// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c4755e5e223f2023d4c34684c2117011d276309e44950a0bd474f1f25564f695
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The language could not be applied to the parser (e.g., ABI version mismatch).
/// </summary>
public class ParserSetupException : ErrorException
{
    public ParserSetupException(string message) : base(message) { }

    public ParserSetupException(string message, Exception innerException) : base(message, innerException) { }
}
