// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:14687d1c1d0c2f444a287af8e41bb8e299062b27c46c2720ef9c04d1c12dc6d0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// A source position — row + column, zero-indexed.
/// </summary>
public sealed record Point
{
    /// <summary>
    /// Zero-indexed row number.
    /// </summary>
    [JsonPropertyName("row")]
    public ulong Row { get; init; } = 0;

    /// <summary>
    /// Zero-indexed column number, in UTF-16 code units.
    /// </summary>
    [JsonPropertyName("column")]
    public ulong Column { get; init; } = 0;


    /// <summary>
    /// Parse a <see cref="Point"/> from a JSON string.
    /// </summary>
    /// <exception cref="TreeSitterLanguagePackException">When the JSON cannot be deserialised.</exception>
    public static Point FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<Point>(json, JsonOptions)
            ?? throw new TreeSitterLanguagePackException($"Failed to parse Point from JSON: deserializer returned null");
        }
        catch (TreeSitterLanguagePackException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new TreeSitterLanguagePackException($"Failed to parse Point from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
