// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:14687d1c1d0c2f444a287af8e41bb8e299062b27c46c2720ef9c04d1c12dc6d0
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A tree-sitter query could not be compiled or executed.
/// </summary>
public class QueryErrorException : ErrorException
{
    public QueryErrorException(string message) : base(message) { }

    public QueryErrorException(string message, Exception innerException) : base(message, innerException) { }
}
