// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0b3e2088d99291afcbfd3389e3471ccf33579c9480061b0ca3aa5e8db085dd92
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A tree-sitter query could not be compiled or executed.
/// </summary>
public class QueryErrorException : ErrorException
{
    public QueryErrorException(string message) : base(message) { }

    public QueryErrorException(string message, Exception innerException) : base(message, innerException) { }
}
