// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e6a18c461da2c31bd3854d90a068c14c4ffb67f3a73f23fe765dad50d70c4266
#nullable enable

using System;

namespace TreeSitterLanguagePack;

public class TreeSitterLanguagePackException : Exception
{
    public int Code { get; }

    public TreeSitterLanguagePackException(int code, string message) : base(message)
    {
        Code = code;
    }

    public TreeSitterLanguagePackException(string message) : base(message)
    {
        Code = 0;
    }

    public TreeSitterLanguagePackException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
