// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e6a18c461da2c31bd3854d90a068c14c4ffb67f3a73f23fe765dad50d70c4266
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import TreeSitterLanguagePack
import RustBridge

/// E2e tests for category: smoke.
final class SmokeTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testSmokeAbl() throws {
        // Smoke test: load abl and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"abl\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeActionscript() throws {
        // Smoke test: load actionscript and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"actionscript\"}")
        _ = try TreeSitterLanguagePack.process(source: "var x:int = 1;", config: configObj)
    }

    func testSmokeAda() throws {
        // Smoke test: load ada and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"ada\"}")
        _ = try TreeSitterLanguagePack.process(source: "procedure Main is begin null; end Main;", config: configObj)
    }

    func testSmokeAgda() throws {
        // Smoke test: load agda and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"agda\"}")
        _ = try TreeSitterLanguagePack.process(source: "module Main where", config: configObj)
    }

    func testSmokeAl() throws {
        // Smoke test: load al and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"al\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeAngular() throws {
        // Smoke test: load angular and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"angular\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeApex() throws {
        // Smoke test: load apex and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"apex\"}")
        _ = try TreeSitterLanguagePack.process(source: "public class Main {}", config: configObj)
    }

    func testSmokeArduino() throws {
        // Smoke test: load arduino and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"arduino\"}")
        _ = try TreeSitterLanguagePack.process(source: "void setup() {}", config: configObj)
    }

    func testSmokeAsciidoc() throws {
        // Smoke test: load asciidoc and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"asciidoc\"}")
        _ = try TreeSitterLanguagePack.process(source: "= Title\n\nParagraph.", config: configObj)
    }

    func testSmokeAsm() throws {
        // Smoke test: load asm and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"asm\"}")
        _ = try TreeSitterLanguagePack.process(source: "mov eax, 1", config: configObj)
    }

    func testSmokeAstro() throws {
        // Smoke test: load astro and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"astro\"}")
        _ = try TreeSitterLanguagePack.process(source: "---\n---\n<p>hello</p>", config: configObj)
    }

    func testSmokeAwk() throws {
        // Smoke test: load awk and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"awk\"}")
        _ = try TreeSitterLanguagePack.process(source: "BEGIN { print \"hello\" }", config: configObj)
    }

    func testSmokeBash() throws {
        // Smoke test: load bash and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"bash\"}")
        _ = try TreeSitterLanguagePack.process(source: "echo hello", config: configObj)
    }

    func testSmokeBass() throws {
        // Smoke test: load bass and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"bass\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeBatch() throws {
        // Smoke test: load batch and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"batch\"}")
        _ = try TreeSitterLanguagePack.process(source: "@echo off\necho hello", config: configObj)
    }

    func testSmokeBeancount() throws {
        // Smoke test: load beancount and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"beancount\"}")
        _ = try TreeSitterLanguagePack.process(source: "2024-01-01 open Assets:Bank USD", config: configObj)
    }

    func testSmokeBibtex() throws {
        // Smoke test: load bibtex and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"bibtex\"}")
        _ = try TreeSitterLanguagePack.process(source: "@article{key, title={A}}", config: configObj)
    }

    func testSmokeBicep() throws {
        // Smoke test: load bicep and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"bicep\"}")
        _ = try TreeSitterLanguagePack.process(source: "param name string", config: configObj)
    }

    func testSmokeBitbake() throws {
        // Smoke test: load bitbake and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"bitbake\"}")
        _ = try TreeSitterLanguagePack.process(source: "DESCRIPTION = \"hello\"", config: configObj)
    }

    func testSmokeBlade() throws {
        // Smoke test: load blade and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"blade\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeBrightscript() throws {
        // Smoke test: load brightscript and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"brightscript\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeBsl() throws {
        // Smoke test: load bsl and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"bsl\"}")
        _ = try TreeSitterLanguagePack.process(source: "Procedure Main() EndProcedure", config: configObj)
    }

    func testSmokeC() throws {
        // Smoke test: load c and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"c\"}")
        _ = try TreeSitterLanguagePack.process(source: "int main() { return 0; }", config: configObj)
    }

    func testSmokeC3() throws {
        // Smoke test: load c3 and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"c3\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeCaddy() throws {
        // Smoke test: load caddy and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"caddy\"}")
        _ = try TreeSitterLanguagePack.process(source: ":8080 {\n\trespond \"Hello\"\n}", config: configObj)
    }

    func testSmokeCairo() throws {
        // Smoke test: load cairo and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"cairo\"}")
        _ = try TreeSitterLanguagePack.process(source: "fn main() {}", config: configObj)
    }

    func testSmokeCapnp() throws {
        // Smoke test: load capnp and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"capnp\"}")
        _ = try TreeSitterLanguagePack.process(source: "@0xabcdef1234567890;", config: configObj)
    }

    func testSmokeCedar() throws {
        // Smoke test: load cedar and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"cedar\"}")
        _ = try TreeSitterLanguagePack.process(source: "permit(principal, action, resource);", config: configObj)
    }

    func testSmokeCedarschema() throws {
        // Smoke test: load cedarschema and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"cedarschema\"}")
        _ = try TreeSitterLanguagePack.process(source: "entity User;", config: configObj)
    }

    func testSmokeCel() throws {
        // Smoke test: load cel and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"cel\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeCfml() throws {
        // Smoke test: load cfml and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"cfml\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeChatito() throws {
        // Smoke test: load chatito and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"chatito\"}")
        _ = try TreeSitterLanguagePack.process(source: "%[greeting]\n    hello", config: configObj)
    }

    func testSmokeChuck() throws {
        // Smoke test: load chuck and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"chuck\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeCircom() throws {
        // Smoke test: load circom and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"circom\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeClarity() throws {
        // Smoke test: load clarity and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"clarity\"}")
        _ = try TreeSitterLanguagePack.process(source: "(define-public (hello) (ok true))", config: configObj)
    }

    func testSmokeClojure() throws {
        // Smoke test: load clojure and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"clojure\"}")
        _ = try TreeSitterLanguagePack.process(source: "(def x 1)", config: configObj)
    }

    func testSmokeCmake() throws {
        // Smoke test: load cmake and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"cmake\"}")
        _ = try TreeSitterLanguagePack.process(source: "cmake_minimum_required(VERSION 3.0)", config: configObj)
    }

    func testSmokeCobol() throws {
        // Smoke test: load cobol and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"cobol\"}")
        _ = try TreeSitterLanguagePack.process(source: "       IDENTIFICATION DIVISION.\n       PROGRAM-ID. HELLO.", config: configObj)
    }

    func testSmokeComment() throws {
        // Smoke test: load comment and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"comment\"}")
        _ = try TreeSitterLanguagePack.process(source: "TODO: fix this", config: configObj)
    }

    func testSmokeCommonlisp() throws {
        // Smoke test: load commonlisp and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"commonlisp\"}")
        _ = try TreeSitterLanguagePack.process(source: "(defun hello () (print \"hello\"))", config: configObj)
    }

    func testSmokeCooklang() throws {
        // Smoke test: load cooklang and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"cooklang\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeCorn() throws {
        // Smoke test: load corn and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"corn\"}")
        _ = try TreeSitterLanguagePack.process(source: "{ key = \"value\" }", config: configObj)
    }

    func testSmokeCpon() throws {
        // Smoke test: load cpon and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"cpon\"}")
        _ = try TreeSitterLanguagePack.process(source: "{\"key\": 1}", config: configObj)
    }

    func testSmokeCpp() throws {
        // Smoke test: load cpp and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"cpp\"}")
        _ = try TreeSitterLanguagePack.process(source: "int main() { return 0; }", config: configObj)
    }

    func testSmokeCrystal() throws {
        // Smoke test: load crystal and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"crystal\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeCsharp() throws {
        // Smoke test: load csharp and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"csharp\"}")
        _ = try TreeSitterLanguagePack.process(source: "class Main {}", config: configObj)
    }

    func testSmokeCss() throws {
        // Smoke test: load css and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"css\"}")
        _ = try TreeSitterLanguagePack.process(source: "body { color: red; }", config: configObj)
    }

    func testSmokeCst() throws {
        // Smoke test: load cst and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"cst\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeCsv() throws {
        // Smoke test: load csv and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"csv\"}")
        _ = try TreeSitterLanguagePack.process(source: "a,b,c\n1,2,3", config: configObj)
    }

    func testSmokeCuda() throws {
        // Smoke test: load cuda and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"cuda\"}")
        _ = try TreeSitterLanguagePack.process(source: "__global__ void kernel() {}", config: configObj)
    }

    func testSmokeCue() throws {
        // Smoke test: load cue and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"cue\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeCylc() throws {
        // Smoke test: load cylc and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"cylc\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeD() throws {
        // Smoke test: load d and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"d\"}")
        _ = try TreeSitterLanguagePack.process(source: "void main() {}", config: configObj)
    }

    func testSmokeDart() throws {
        // Smoke test: load dart and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"dart\"}")
        _ = try TreeSitterLanguagePack.process(source: "void main() {}", config: configObj)
    }

    func testSmokeDesktop() throws {
        // Smoke test: load desktop and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"desktop\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeDevicetree() throws {
        // Smoke test: load devicetree and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"devicetree\"}")
        _ = try TreeSitterLanguagePack.process(source: "/dts-v1/;\n/ { };", config: configObj)
    }

    func testSmokeDhall() throws {
        // Smoke test: load dhall and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"dhall\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeDiff() throws {
        // Smoke test: load diff and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"diff\"}")
        _ = try TreeSitterLanguagePack.process(source: "--- a/file\n+++ b/file\n@@ -1 +1 @@\n-old\n+new", config: configObj)
    }

    func testSmokeDjot() throws {
        // Smoke test: load djot and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"djot\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeDockerfile() throws {
        // Smoke test: load dockerfile and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"dockerfile\"}")
        _ = try TreeSitterLanguagePack.process(source: "FROM alpine", config: configObj)
    }

    func testSmokeDot() throws {
        // Smoke test: load dot and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"dot\"}")
        _ = try TreeSitterLanguagePack.process(source: "digraph G { A -> B; }", config: configObj)
    }

    func testSmokeDoxygen() throws {
        // Smoke test: load doxygen and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"doxygen\"}")
        _ = try TreeSitterLanguagePack.process(source: "/** @brief A function */", config: configObj)
    }

    func testSmokeDtd() throws {
        // Smoke test: load dtd and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"dtd\"}")
        _ = try TreeSitterLanguagePack.process(source: "<!ELEMENT note (body)>", config: configObj)
    }

    func testSmokeEarthfile() throws {
        // Smoke test: load earthfile and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"earthfile\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeEbnf() throws {
        // Smoke test: load ebnf and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"ebnf\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeEditorconfig() throws {
        // Smoke test: load editorconfig and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"editorconfig\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeEds() throws {
        // Smoke test: load eds and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"eds\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeEex() throws {
        // Smoke test: load eex and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"eex\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeElisp() throws {
        // Smoke test: load elisp and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"elisp\"}")
        _ = try TreeSitterLanguagePack.process(source: "(defun hello () (message \"hello\"))", config: configObj)
    }

    func testSmokeElixir() throws {
        // Smoke test: load elixir and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"elixir\"}")
        _ = try TreeSitterLanguagePack.process(source: "IO.puts(\"hello\")", config: configObj)
    }

    func testSmokeElm() throws {
        // Smoke test: load elm and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"elm\"}")
        _ = try TreeSitterLanguagePack.process(source: "module Main exposing (..)", config: configObj)
    }

    func testSmokeElsa() throws {
        // Smoke test: load elsa and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"elsa\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeElvish() throws {
        // Smoke test: load elvish and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"elvish\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeEmbeddedtemplate() throws {
        // Smoke test: load embeddedtemplate and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"embeddedtemplate\"}")
        _ = try TreeSitterLanguagePack.process(source: "<%= value %>", config: configObj)
    }

    func testSmokeEnforce() throws {
        // Smoke test: load enforce and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"enforce\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeErlang() throws {
        // Smoke test: load erlang and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"erlang\"}")
        _ = try TreeSitterLanguagePack.process(source: "main() -> ok.", config: configObj)
    }

    func testSmokeFacility() throws {
        // Smoke test: load facility and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"facility\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeFaust() throws {
        // Smoke test: load faust and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"faust\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeFennel() throws {
        // Smoke test: load fennel and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"fennel\"}")
        _ = try TreeSitterLanguagePack.process(source: "(fn hello [] (print :hello))", config: configObj)
    }

    func testSmokeFidl() throws {
        // Smoke test: load fidl and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"fidl\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeFirrtl() throws {
        // Smoke test: load firrtl and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"firrtl\"}")
        _ = try TreeSitterLanguagePack.process(source: "circuit Main :", config: configObj)
    }

    func testSmokeFish() throws {
        // Smoke test: load fish and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"fish\"}")
        _ = try TreeSitterLanguagePack.process(source: "echo hello", config: configObj)
    }

    func testSmokeFoam() throws {
        // Smoke test: load foam and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"foam\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeForth() throws {
        // Smoke test: load forth and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"forth\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeFortran() throws {
        // Smoke test: load fortran and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"fortran\"}")
        _ = try TreeSitterLanguagePack.process(source: "program main\nend program main", config: configObj)
    }

    func testSmokeFsharp() throws {
        // Smoke test: load fsharp and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"fsharp\"}")
        _ = try TreeSitterLanguagePack.process(source: "let x = 1", config: configObj)
    }

    func testSmokeFsharpSignature() throws {
        // Smoke test: load fsharp_signature and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"fsharp_signature\"}")
        _ = try TreeSitterLanguagePack.process(source: "val x: int", config: configObj)
    }

    func testSmokeFunc() throws {
        // Smoke test: load func and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"func\"}")
        _ = try TreeSitterLanguagePack.process(source: "() recv_internal() {}", config: configObj)
    }

    func testSmokeGap() throws {
        // Smoke test: load gap and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"gap\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeGdscript() throws {
        // Smoke test: load gdscript and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"gdscript\"}")
        _ = try TreeSitterLanguagePack.process(source: "extends Node\nfunc _ready():\n\tpass", config: configObj)
    }

    func testSmokeGdshader() throws {
        // Smoke test: load gdshader and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"gdshader\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeGherkin() throws {
        // Smoke test: load gherkin and parse a simple feature
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"gherkin\"}")
        _ = try TreeSitterLanguagePack.process(source: "Feature: Calculator\n  Scenario: Add numbers\n    Given I have entered 1\n    When I add 2\n    Then the result should be 3\n", config: configObj)
    }

    func testSmokeGitConfig() throws {
        // Smoke test: load git_config and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"git_config\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeGitRebase() throws {
        // Smoke test: load git_rebase and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"git_rebase\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeGitattributes() throws {
        // Smoke test: load gitattributes and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"gitattributes\"}")
        _ = try TreeSitterLanguagePack.process(source: "*.txt text", config: configObj)
    }

    func testSmokeGitcommit() throws {
        // Smoke test: load gitcommit and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"gitcommit\"}")
        _ = try TreeSitterLanguagePack.process(source: "feat: add feature\n\nBody text", config: configObj)
    }

    func testSmokeGitignore() throws {
        // Smoke test: load gitignore and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"gitignore\"}")
        _ = try TreeSitterLanguagePack.process(source: "*.o\n*.log", config: configObj)
    }

    func testSmokeGleam() throws {
        // Smoke test: load gleam and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"gleam\"}")
        _ = try TreeSitterLanguagePack.process(source: "pub fn main() { }", config: configObj)
    }

    func testSmokeGlimmer() throws {
        // Smoke test: load glimmer and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"glimmer\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeGlsl() throws {
        // Smoke test: load glsl and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"glsl\"}")
        _ = try TreeSitterLanguagePack.process(source: "void main() { gl_Position = vec4(0.0); }", config: configObj)
    }

    func testSmokeGn() throws {
        // Smoke test: load gn and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"gn\"}")
        _ = try TreeSitterLanguagePack.process(source: "group(\"hello\") {}", config: configObj)
    }

    func testSmokeGnuplot() throws {
        // Smoke test: load gnuplot and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"gnuplot\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeGo() throws {
        // Smoke test: load go and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"go\"}")
        _ = try TreeSitterLanguagePack.process(source: "package main", config: configObj)
    }

    func testSmokeGodotResource() throws {
        // Smoke test: load godot_resource and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"godot_resource\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeGomod() throws {
        // Smoke test: load gomod and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"gomod\"}")
        _ = try TreeSitterLanguagePack.process(source: "module example.com/hello\n\ngo 1.21", config: configObj)
    }

    func testSmokeGosum() throws {
        // Smoke test: load gosum and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"gosum\"}")
        _ = try TreeSitterLanguagePack.process(source: "example.com/pkg v1.0.0 h1:abc=", config: configObj)
    }

    func testSmokeGotmpl() throws {
        // Smoke test: load gotmpl and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"gotmpl\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeGowork() throws {
        // Smoke test: load gowork and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"gowork\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeGpg() throws {
        // Smoke test: load gpg and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"gpg\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeGraphql() throws {
        // Smoke test: load graphql and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"graphql\"}")
        _ = try TreeSitterLanguagePack.process(source: "type Query { hello: String }", config: configObj)
    }

    func testSmokeGren() throws {
        // Smoke test: load gren and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"gren\"}")
        _ = try TreeSitterLanguagePack.process(source: "module Main exposing (..)", config: configObj)
    }

    func testSmokeGroovy() throws {
        // Smoke test: load groovy and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"groovy\"}")
        _ = try TreeSitterLanguagePack.process(source: "def x = 1", config: configObj)
    }

    func testSmokeGstlaunch() throws {
        // Smoke test: load gstlaunch and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"gstlaunch\"}")
        _ = try TreeSitterLanguagePack.process(source: "fakesrc ! fakesink", config: configObj)
    }

    func testSmokeHack() throws {
        // Smoke test: load hack and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"hack\"}")
        _ = try TreeSitterLanguagePack.process(source: "<?hh\nfunction main(): void {}", config: configObj)
    }

    func testSmokeHare() throws {
        // Smoke test: load hare and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"hare\"}")
        _ = try TreeSitterLanguagePack.process(source: "export fn main() void = void;", config: configObj)
    }

    func testSmokeHaskell() throws {
        // Smoke test: load haskell and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"haskell\"}")
        _ = try TreeSitterLanguagePack.process(source: "main = putStrLn \"hello\"", config: configObj)
    }

    func testSmokeHaxe() throws {
        // Smoke test: load haxe and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"haxe\"}")
        _ = try TreeSitterLanguagePack.process(source: "class Main { static function main() {} }", config: configObj)
    }

    func testSmokeHcl() throws {
        // Smoke test: load hcl and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"hcl\"}")
        _ = try TreeSitterLanguagePack.process(source: "variable \"name\" { type = string }", config: configObj)
    }

    func testSmokeHeex() throws {
        // Smoke test: load heex and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"heex\"}")
        _ = try TreeSitterLanguagePack.process(source: "<%= @greeting %>", config: configObj)
    }

    func testSmokeHjson() throws {
        // Smoke test: load hjson and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"hjson\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeHlsl() throws {
        // Smoke test: load hlsl and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"hlsl\"}")
        _ = try TreeSitterLanguagePack.process(source: "float4 main() : SV_Target { return 0; }", config: configObj)
    }

    func testSmokeHocon() throws {
        // Smoke test: load hocon and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"hocon\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeHoon() throws {
        // Smoke test: load hoon and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"hoon\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeHtml() throws {
        // Smoke test: load html and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"html\"}")
        _ = try TreeSitterLanguagePack.process(source: "<p>hello</p>", config: configObj)
    }

    func testSmokeHtmldjango() throws {
        // Smoke test: load htmldjango and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"htmldjango\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeHttp() throws {
        // Smoke test: load http and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"http\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeHurl() throws {
        // Smoke test: load hurl and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"hurl\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeHyprlang() throws {
        // Smoke test: load hyprlang and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"hyprlang\"}")
        _ = try TreeSitterLanguagePack.process(source: "general { border_size = 1 }", config: configObj)
    }

    func testSmokeIdris() throws {
        // Smoke test: load idris and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"idris\"}")
        _ = try TreeSitterLanguagePack.process(source: "module Main", config: configObj)
    }

    func testSmokeIni() throws {
        // Smoke test: load ini and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"ini\"}")
        _ = try TreeSitterLanguagePack.process(source: "[section]\nkey = value", config: configObj)
    }

    func testSmokeIspc() throws {
        // Smoke test: load ispc and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"ispc\"}")
        _ = try TreeSitterLanguagePack.process(source: "export void main() {}", config: configObj)
    }

    func testSmokeJai() throws {
        // Smoke test: load jai and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"jai\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeJanet() throws {
        // Smoke test: load janet and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"janet\"}")
        _ = try TreeSitterLanguagePack.process(source: "(print \"hello\")", config: configObj)
    }

    func testSmokeJava() throws {
        // Smoke test: load java and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"java\"}")
        _ = try TreeSitterLanguagePack.process(source: "class Main {}", config: configObj)
    }

    func testSmokeJavadoc() throws {
        // Smoke test: load javadoc and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"javadoc\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeJavascript() throws {
        // Smoke test: load javascript and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"javascript\"}")
        _ = try TreeSitterLanguagePack.process(source: "console.log('hello');", config: configObj)
    }

    func testSmokeJinja2() throws {
        // Smoke test: load jinja2 and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"jinja2\"}")
        _ = try TreeSitterLanguagePack.process(source: "{{ variable }}", config: configObj)
    }

    func testSmokeJq() throws {
        // Smoke test: load jq and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"jq\"}")
        _ = try TreeSitterLanguagePack.process(source: ".[] | select(.key)", config: configObj)
    }

    func testSmokeJsdoc() throws {
        // Smoke test: load jsdoc and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"jsdoc\"}")
        _ = try TreeSitterLanguagePack.process(source: "/** @param {string} name */", config: configObj)
    }

    func testSmokeJson() throws {
        // Smoke test: load json and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"json\"}")
        _ = try TreeSitterLanguagePack.process(source: "{\"key\": \"value\"}", config: configObj)
    }

    func testSmokeJson5() throws {
        // Smoke test: load json5 and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"json5\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeJsonnet() throws {
        // Smoke test: load jsonnet and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"jsonnet\"}")
        _ = try TreeSitterLanguagePack.process(source: "{ key: 'value' }", config: configObj)
    }

    func testSmokeJulia() throws {
        // Smoke test: load julia and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"julia\"}")
        _ = try TreeSitterLanguagePack.process(source: "function main() end", config: configObj)
    }

    func testSmokeJust() throws {
        // Smoke test: load just and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"just\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeKcl() throws {
        // Smoke test: load kcl and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"kcl\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeKconfig() throws {
        // Smoke test: load kconfig and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"kconfig\"}")
        _ = try TreeSitterLanguagePack.process(source: "config FOO\n\tbool \"Enable foo\"", config: configObj)
    }

    func testSmokeKdl() throws {
        // Smoke test: load kdl and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"kdl\"}")
        _ = try TreeSitterLanguagePack.process(source: "node \"value\"", config: configObj)
    }

    func testSmokeKotlin() throws {
        // Smoke test: load kotlin and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"kotlin\"}")
        _ = try TreeSitterLanguagePack.process(source: "fun main() {}", config: configObj)
    }

    func testSmokeLatex() throws {
        // Smoke test: load latex and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"latex\"}")
        _ = try TreeSitterLanguagePack.process(source: "\\documentclass{article}\n\\begin{document}\nHello\n\\end{document}", config: configObj)
    }

    func testSmokeLean() throws {
        // Smoke test: load lean and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"lean\"}")
        _ = try TreeSitterLanguagePack.process(source: "def main : IO Unit := pure ()", config: configObj)
    }

    func testSmokeLedger() throws {
        // Smoke test: load ledger and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"ledger\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeLess() throws {
        // Smoke test: load less and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"less\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeLinkerscript() throws {
        // Smoke test: load linkerscript and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"linkerscript\"}")
        _ = try TreeSitterLanguagePack.process(source: "SECTIONS { .text : { *(.text) } }", config: configObj)
    }

    func testSmokeLiquid() throws {
        // Smoke test: load liquid and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"liquid\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeLlvm() throws {
        // Smoke test: load llvm and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"llvm\"}")
        _ = try TreeSitterLanguagePack.process(source: "define i32 @main() { ret i32 0 }", config: configObj)
    }

    func testSmokeLua() throws {
        // Smoke test: load lua and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"lua\"}")
        _ = try TreeSitterLanguagePack.process(source: "print('hello')", config: configObj)
    }

    func testSmokeLuadoc() throws {
        // Smoke test: load luadoc and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"luadoc\"}")
        _ = try TreeSitterLanguagePack.process(source: "---@param name string", config: configObj)
    }

    func testSmokeLuap() throws {
        // Smoke test: load luap and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"luap\"}")
        _ = try TreeSitterLanguagePack.process(source: "[a-z]+", config: configObj)
    }

    func testSmokeLuau() throws {
        // Smoke test: load luau and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"luau\"}")
        _ = try TreeSitterLanguagePack.process(source: "local x: number = 1", config: configObj)
    }

    func testSmokeMagik() throws {
        // Smoke test: load magik and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"magik\"}")
        _ = try TreeSitterLanguagePack.process(source: "_method object.hello\n_endmethod", config: configObj)
    }

    func testSmokeMake() throws {
        // Smoke test: load make and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"make\"}")
        _ = try TreeSitterLanguagePack.process(source: "all:\n\techo hello", config: configObj)
    }

    func testSmokeMarkdown() throws {
        // Smoke test: load markdown and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"markdown\"}")
        _ = try TreeSitterLanguagePack.process(source: "# Hello\n\nWorld", config: configObj)
    }

    func testSmokeMarkdownInline() throws {
        // Smoke test: load markdown_inline and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"markdown_inline\"}")
        _ = try TreeSitterLanguagePack.process(source: "**bold** and *italic*", config: configObj)
    }

    func testSmokeMatlab() throws {
        // Smoke test: load matlab and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"matlab\"}")
        _ = try TreeSitterLanguagePack.process(source: "function y = hello(x)\ny = x;\nend", config: configObj)
    }

    func testSmokeMermaid() throws {
        // Smoke test: load mermaid and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"mermaid\"}")
        _ = try TreeSitterLanguagePack.process(source: "graph TD\nA --> B", config: configObj)
    }

    func testSmokeMeson() throws {
        // Smoke test: load meson and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"meson\"}")
        _ = try TreeSitterLanguagePack.process(source: "project('hello', 'c')", config: configObj)
    }

    func testSmokeMlir() throws {
        // Smoke test: load mlir and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"mlir\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeMojo() throws {
        // Smoke test: load mojo and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"mojo\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeMove() throws {
        // Smoke test: load move and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"move\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeNasm() throws {
        // Smoke test: load nasm and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"nasm\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeNetlinx() throws {
        // Smoke test: load netlinx and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"netlinx\"}")
        _ = try TreeSitterLanguagePack.process(source: "PROGRAM_NAME='hello'", config: configObj)
    }

    func testSmokeNginx() throws {
        // Smoke test: load nginx and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"nginx\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeNickel() throws {
        // Smoke test: load nickel and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"nickel\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeNim() throws {
        // Smoke test: load nim and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"nim\"}")
        _ = try TreeSitterLanguagePack.process(source: "echo \"hello\"", config: configObj)
    }

    func testSmokeNinja() throws {
        // Smoke test: load ninja and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"ninja\"}")
        _ = try TreeSitterLanguagePack.process(source: "rule cc\n  command = cc $in -o $out", config: configObj)
    }

    func testSmokeNix() throws {
        // Smoke test: load nix and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"nix\"}")
        _ = try TreeSitterLanguagePack.process(source: "{ pkgs ? import <nixpkgs> {} }: pkgs.hello", config: configObj)
    }

    func testSmokeNorg() throws {
        // Smoke test: load norg and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"norg\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeNorgMeta() throws {
        // Smoke test: load norg_meta and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"norg_meta\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeNqc() throws {
        // Smoke test: load nqc and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"nqc\"}")
        _ = try TreeSitterLanguagePack.process(source: "task main() {}", config: configObj)
    }

    func testSmokeNushell() throws {
        // Smoke test: load nushell and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"nushell\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeObjc() throws {
        // Smoke test: load objc and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"objc\"}")
        _ = try TreeSitterLanguagePack.process(source: "@interface Main @end", config: configObj)
    }

    func testSmokeOcaml() throws {
        // Smoke test: load ocaml and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"ocaml\"}")
        _ = try TreeSitterLanguagePack.process(source: "let () = print_endline \"hello\"", config: configObj)
    }

    func testSmokeOcamlInterface() throws {
        // Smoke test: load ocaml_interface and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"ocaml_interface\"}")
        _ = try TreeSitterLanguagePack.process(source: "val x : int", config: configObj)
    }

    func testSmokeOcamllex() throws {
        // Smoke test: load ocamllex and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"ocamllex\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeOdin() throws {
        // Smoke test: load odin and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"odin\"}")
        _ = try TreeSitterLanguagePack.process(source: "package main", config: configObj)
    }

    func testSmokeOpenscad() throws {
        // Smoke test: load openscad and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"openscad\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeOrg() throws {
        // Smoke test: load org and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"org\"}")
        _ = try TreeSitterLanguagePack.process(source: "* Hello\nWorld", config: configObj)
    }

    func testSmokePascal() throws {
        // Smoke test: load pascal and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"pascal\"}")
        _ = try TreeSitterLanguagePack.process(source: "program Hello; begin end.", config: configObj)
    }

    func testSmokePem() throws {
        // Smoke test: load pem and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"pem\"}")
        _ = try TreeSitterLanguagePack.process(source: "-----BEGIN CERTIFICATE-----\ndata\n-----END CERTIFICATE-----", config: configObj)
    }

    func testSmokePerl() throws {
        // Smoke test: load perl and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"perl\"}")
        _ = try TreeSitterLanguagePack.process(source: "print 'hello';", config: configObj)
    }

    func testSmokePgn() throws {
        // Smoke test: load pgn and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"pgn\"}")
        _ = try TreeSitterLanguagePack.process(source: "1. e4 e5 *", config: configObj)
    }

    func testSmokePhp() throws {
        // Smoke test: load php and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"php\"}")
        _ = try TreeSitterLanguagePack.process(source: "<?php echo 'hello'; ?>", config: configObj)
    }

    func testSmokePhpdoc() throws {
        // Smoke test: load phpdoc and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"phpdoc\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokePkl() throws {
        // Smoke test: load pkl and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"pkl\"}")
        _ = try TreeSitterLanguagePack.process(source: "name = \"hello\"", config: configObj)
    }

    func testSmokePo() throws {
        // Smoke test: load po and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"po\"}")
        _ = try TreeSitterLanguagePack.process(source: "msgid \"hello\"\nmsgstr \"world\"", config: configObj)
    }

    func testSmokePoeFilter() throws {
        // Smoke test: load poe_filter and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"poe_filter\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokePony() throws {
        // Smoke test: load pony and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"pony\"}")
        _ = try TreeSitterLanguagePack.process(source: "actor Main\n  new create(env: Env) => None", config: configObj)
    }

    func testSmokePostscript() throws {
        // Smoke test: load postscript and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"postscript\"}")
        _ = try TreeSitterLanguagePack.process(source: "/hello { (Hello) show } def", config: configObj)
    }

    func testSmokePowershell() throws {
        // Smoke test: load powershell and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"powershell\"}")
        _ = try TreeSitterLanguagePack.process(source: "Write-Host 'hello'", config: configObj)
    }

    func testSmokePrintf() throws {
        // Smoke test: load printf and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"printf\"}")
        _ = try TreeSitterLanguagePack.process(source: "%d %s", config: configObj)
    }

    func testSmokePrisma() throws {
        // Smoke test: load prisma and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"prisma\"}")
        _ = try TreeSitterLanguagePack.process(source: "model User { id Int @id }", config: configObj)
    }

    func testSmokeProlog() throws {
        // Smoke test: load prolog and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"prolog\"}")
        _ = try TreeSitterLanguagePack.process(source: "hello :- write('hello'), nl.", config: configObj)
    }

    func testSmokePromql() throws {
        // Smoke test: load promql and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"promql\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeProperties() throws {
        // Smoke test: load properties and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"properties\"}")
        _ = try TreeSitterLanguagePack.process(source: "key=value", config: configObj)
    }

    func testSmokeProto() throws {
        // Smoke test: load proto and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"proto\"}")
        _ = try TreeSitterLanguagePack.process(source: "syntax = \"proto3\";", config: configObj)
    }

    func testSmokePrql() throws {
        // Smoke test: load prql and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"prql\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokePsv() throws {
        // Smoke test: load psv and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"psv\"}")
        _ = try TreeSitterLanguagePack.process(source: "a|b|c\n1|2|3", config: configObj)
    }

    func testSmokePug() throws {
        // Smoke test: load pug and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"pug\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokePuppet() throws {
        // Smoke test: load puppet and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"puppet\"}")
        _ = try TreeSitterLanguagePack.process(source: "notify { 'hello': }", config: configObj)
    }

    func testSmokePurescript() throws {
        // Smoke test: load purescript and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"purescript\"}")
        _ = try TreeSitterLanguagePack.process(source: "module Main where", config: configObj)
    }

    func testSmokePymanifest() throws {
        // Smoke test: load pymanifest and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"pymanifest\"}")
        _ = try TreeSitterLanguagePack.process(source: "include *.txt", config: configObj)
    }

    func testSmokePython() throws {
        // Smoke test: load python and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"python\"}")
        _ = try TreeSitterLanguagePack.process(source: "print('hello')", config: configObj)
    }

    func testSmokeQl() throws {
        // Smoke test: load ql and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"ql\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeQmldir() throws {
        // Smoke test: load qmldir and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"qmldir\"}")
        _ = try TreeSitterLanguagePack.process(source: "module Example", config: configObj)
    }

    func testSmokeQmljs() throws {
        // Smoke test: load qmljs and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"qmljs\"}")
        _ = try TreeSitterLanguagePack.process(source: "import QtQuick 2.0\nItem {}", config: configObj)
    }

    func testSmokeQuery() throws {
        // Smoke test: load query and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"query\"}")
        _ = try TreeSitterLanguagePack.process(source: "(identifier) @name", config: configObj)
    }

    func testSmokeR() throws {
        // Smoke test: load r and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"r\"}")
        _ = try TreeSitterLanguagePack.process(source: "print('hello')", config: configObj)
    }

    func testSmokeRacket() throws {
        // Smoke test: load racket and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"racket\"}")
        _ = try TreeSitterLanguagePack.process(source: "#lang racket\n(define x 1)", config: configObj)
    }

    func testSmokeRasi() throws {
        // Smoke test: load rasi and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"rasi\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeRazor() throws {
        // Smoke test: load razor and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"razor\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeRbs() throws {
        // Smoke test: load rbs and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"rbs\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeRe2c() throws {
        // Smoke test: load re2c and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"re2c\"}")
        _ = try TreeSitterLanguagePack.process(source: "/*!re2c\n  [a-z]+ { return; }\n*/", config: configObj)
    }

    func testSmokeReadline() throws {
        // Smoke test: load readline and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"readline\"}")
        _ = try TreeSitterLanguagePack.process(source: "set editing-mode vi", config: configObj)
    }

    func testSmokeRegex() throws {
        // Smoke test: load regex and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"regex\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeRego() throws {
        // Smoke test: load rego and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"rego\"}")
        _ = try TreeSitterLanguagePack.process(source: "package main\ndefault allow = false", config: configObj)
    }

    func testSmokeRequirements() throws {
        // Smoke test: load requirements and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"requirements\"}")
        _ = try TreeSitterLanguagePack.process(source: "flask>=2.0", config: configObj)
    }

    func testSmokeRescript() throws {
        // Smoke test: load rescript and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"rescript\"}")
        _ = try TreeSitterLanguagePack.process(source: "let x = 1", config: configObj)
    }

    func testSmokeRobot() throws {
        // Smoke test: load robot and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"robot\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeRoc() throws {
        // Smoke test: load roc and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"roc\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeRon() throws {
        // Smoke test: load ron and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"ron\"}")
        _ = try TreeSitterLanguagePack.process(source: "(key: \"value\")", config: configObj)
    }

    func testSmokeRst() throws {
        // Smoke test: load rst and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"rst\"}")
        _ = try TreeSitterLanguagePack.process(source: "Hello\n=====\n\nWorld", config: configObj)
    }

    func testSmokeRtf() throws {
        // Smoke test: load rtf and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"rtf\"}")
        _ = try TreeSitterLanguagePack.process(source: "{\\rtf1 hello}", config: configObj)
    }

    func testSmokeRuby() throws {
        // Smoke test: load ruby and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"ruby\"}")
        _ = try TreeSitterLanguagePack.process(source: "puts 'hello'", config: configObj)
    }

    func testSmokeRust() throws {
        // Smoke test: load rust and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"rust\"}")
        _ = try TreeSitterLanguagePack.process(source: "fn main() {}", config: configObj)
    }

    func testSmokeScala() throws {
        // Smoke test: load scala and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"scala\"}")
        _ = try TreeSitterLanguagePack.process(source: "object Main", config: configObj)
    }

    func testSmokeScheme() throws {
        // Smoke test: load scheme and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"scheme\"}")
        _ = try TreeSitterLanguagePack.process(source: "(define x 1)", config: configObj)
    }

    func testSmokeScss() throws {
        // Smoke test: load scss and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"scss\"}")
        _ = try TreeSitterLanguagePack.process(source: "$color: red;\nbody { color: $color; }", config: configObj)
    }

    func testSmokeSlang() throws {
        // Smoke test: load slang and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"slang\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeSmali() throws {
        // Smoke test: load smali and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"smali\"}")
        _ = try TreeSitterLanguagePack.process(source: ".class public LMain;\n.super Ljava/lang/Object;", config: configObj)
    }

    func testSmokeSmalltalk() throws {
        // Smoke test: load smalltalk and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"smalltalk\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeSmithy() throws {
        // Smoke test: load smithy and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"smithy\"}")
        _ = try TreeSitterLanguagePack.process(source: "namespace example\nstring MyString", config: configObj)
    }

    func testSmokeSml() throws {
        // Smoke test: load sml and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"sml\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeSnakemake() throws {
        // Smoke test: load snakemake and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"snakemake\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeSolidity() throws {
        // Smoke test: load solidity and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"solidity\"}")
        _ = try TreeSitterLanguagePack.process(source: "pragma solidity ^0.8.0;\ncontract Main {}", config: configObj)
    }

    func testSmokeSouffle() throws {
        // Smoke test: load souffle and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"souffle\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeSourcepawn() throws {
        // Smoke test: load sourcepawn and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"sourcepawn\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeSparql() throws {
        // Smoke test: load sparql and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"sparql\"}")
        _ = try TreeSitterLanguagePack.process(source: "SELECT ?s WHERE { ?s ?p ?o }", config: configObj)
    }

    func testSmokeSql() throws {
        // Smoke test: load sql and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"sql\"}")
        _ = try TreeSitterLanguagePack.process(source: "SELECT 1;", config: configObj)
    }

    func testSmokeSqlBigquery() throws {
        // Smoke test: load sql_bigquery and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"sql_bigquery\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeSquirrel() throws {
        // Smoke test: load squirrel and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"squirrel\"}")
        _ = try TreeSitterLanguagePack.process(source: "function main() {}", config: configObj)
    }

    func testSmokeSshConfig() throws {
        // Smoke test: load ssh_config and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"ssh_config\"}")
        _ = try TreeSitterLanguagePack.process(source: "Host example\n  HostName example.com", config: configObj)
    }

    func testSmokeStan() throws {
        // Smoke test: load stan and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"stan\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeStarlark() throws {
        // Smoke test: load starlark and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"starlark\"}")
        _ = try TreeSitterLanguagePack.process(source: "def hello(): pass", config: configObj)
    }

    func testSmokeSuperhtml() throws {
        // Smoke test: load superhtml and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"superhtml\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeSvelte() throws {
        // Smoke test: load svelte and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"svelte\"}")
        _ = try TreeSitterLanguagePack.process(source: "<script>let x = 1;</script>", config: configObj)
    }

    func testSmokeSway() throws {
        // Smoke test: load sway and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"sway\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeSwift() throws {
        // Smoke test: load swift and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"swift\"}")
        _ = try TreeSitterLanguagePack.process(source: "print(\"hello\")", config: configObj)
    }

    func testSmokeSystemverilog() throws {
        // Smoke test: load systemverilog and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"systemverilog\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeTablegen() throws {
        // Smoke test: load tablegen and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"tablegen\"}")
        _ = try TreeSitterLanguagePack.process(source: "def Hello : Base {}", config: configObj)
    }

    func testSmokeTact() throws {
        // Smoke test: load tact and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"tact\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeTcl() throws {
        // Smoke test: load tcl and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"tcl\"}")
        _ = try TreeSitterLanguagePack.process(source: "puts hello", config: configObj)
    }

    func testSmokeTeal() throws {
        // Smoke test: load teal and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"teal\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeTempl() throws {
        // Smoke test: load templ and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"templ\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeTera() throws {
        // Smoke test: load tera and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"tera\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeTerraform() throws {
        // Smoke test: load terraform and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"terraform\"}")
        _ = try TreeSitterLanguagePack.process(source: "resource \"null_resource\" \"main\" {}", config: configObj)
    }

    func testSmokeTest() throws {
        // Smoke test: load test and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"test\"}")
        _ = try TreeSitterLanguagePack.process(source: "===========\nTest\n===========\n---\n(node)", config: configObj)
    }

    func testSmokeTextproto() throws {
        // Smoke test: load textproto and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"textproto\"}")
        _ = try TreeSitterLanguagePack.process(source: "key: \"value\"", config: configObj)
    }

    func testSmokeThrift() throws {
        // Smoke test: load thrift and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"thrift\"}")
        _ = try TreeSitterLanguagePack.process(source: "service HelloService {}", config: configObj)
    }

    func testSmokeTlaplus() throws {
        // Smoke test: load tlaplus and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"tlaplus\"}")
        _ = try TreeSitterLanguagePack.process(source: "---- MODULE Main ----\n====", config: configObj)
    }

    func testSmokeTmux() throws {
        // Smoke test: load tmux and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"tmux\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeTodotxt() throws {
        // Smoke test: load todotxt and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"todotxt\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeToml() throws {
        // Smoke test: load toml and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"toml\"}")
        _ = try TreeSitterLanguagePack.process(source: "key = \"value\"", config: configObj)
    }

    func testSmokeTsv() throws {
        // Smoke test: load tsv and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"tsv\"}")
        _ = try TreeSitterLanguagePack.process(source: "a\tb\tc\n1\t2\t3", config: configObj)
    }

    func testSmokeTsx() throws {
        // Smoke test: load tsx and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"tsx\"}")
        _ = try TreeSitterLanguagePack.process(source: "const App = () => <div />;", config: configObj)
    }

    func testSmokeTurtle() throws {
        // Smoke test: load turtle and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"turtle\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeTwig() throws {
        // Smoke test: load twig and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"twig\"}")
        _ = try TreeSitterLanguagePack.process(source: "{{ variable }}", config: configObj)
    }

    func testSmokeTypescript() throws {
        // Smoke test: load typescript and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"typescript\"}")
        _ = try TreeSitterLanguagePack.process(source: "const x: number = 42;", config: configObj)
    }

    func testSmokeTypespec() throws {
        // Smoke test: load typespec and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"typespec\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeTyposcript() throws {
        // Smoke test: load typoscript and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"typoscript\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeTypst() throws {
        // Smoke test: load typst and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"typst\"}")
        _ = try TreeSitterLanguagePack.process(source: "#let x = 1", config: configObj)
    }

    func testSmokeUdev() throws {
        // Smoke test: load udev and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"udev\"}")
        _ = try TreeSitterLanguagePack.process(source: "ACTION==\"add\", KERNEL==\"sd*\"", config: configObj)
    }

    func testSmokeUngrammar() throws {
        // Smoke test: load ungrammar and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"ungrammar\"}")
        _ = try TreeSitterLanguagePack.process(source: "Root = Item*\nItem = 'token'", config: configObj)
    }

    func testSmokeUxntal() throws {
        // Smoke test: load uxntal and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"uxntal\"}")
        _ = try TreeSitterLanguagePack.process(source: "|0100 LIT 01", config: configObj)
    }

    func testSmokeV() throws {
        // Smoke test: load v and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"v\"}")
        _ = try TreeSitterLanguagePack.process(source: "fn main() {}", config: configObj)
    }

    func testSmokeVb() throws {
        // Smoke test: load vb and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"vb\"}")
        _ = try TreeSitterLanguagePack.process(source: "Module Main\nEnd Module", config: configObj)
    }

    func testSmokeVerilog() throws {
        // Smoke test: load verilog and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"verilog\"}")
        _ = try TreeSitterLanguagePack.process(source: "module main; endmodule", config: configObj)
    }

    func testSmokeVhdl() throws {
        // Smoke test: load vhdl and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"vhdl\"}")
        _ = try TreeSitterLanguagePack.process(source: "entity main is end main;", config: configObj)
    }

    func testSmokeVhs() throws {
        // Smoke test: load vhs and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"vhs\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeVim() throws {
        // Smoke test: load vim and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"vim\"}")
        _ = try TreeSitterLanguagePack.process(source: "echo 'hello'", config: configObj)
    }

    func testSmokeVimdoc() throws {
        // Smoke test: load vimdoc and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"vimdoc\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeVrl() throws {
        // Smoke test: load vrl and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"vrl\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeVue() throws {
        // Smoke test: load vue and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"vue\"}")
        _ = try TreeSitterLanguagePack.process(source: "<template><div>hello</div></template>", config: configObj)
    }

    func testSmokeWast() throws {
        // Smoke test: load wast and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"wast\"}")
        _ = try TreeSitterLanguagePack.process(source: "(module)", config: configObj)
    }

    func testSmokeWat() throws {
        // Smoke test: load wat and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"wat\"}")
        _ = try TreeSitterLanguagePack.process(source: "(module)", config: configObj)
    }

    func testSmokeWgsl() throws {
        // Smoke test: load wgsl and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"wgsl\"}")
        _ = try TreeSitterLanguagePack.process(source: "@vertex fn main() -> @builtin(position) vec4f { return vec4f(); }", config: configObj)
    }

    func testSmokeWgslBevy() throws {
        // Smoke test: load wgsl_bevy and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"wgsl_bevy\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeWit() throws {
        // Smoke test: load wit and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"wit\"}")
        _ = try TreeSitterLanguagePack.process(source: "package example:pkg;", config: configObj)
    }

    func testSmokeX86asm() throws {
        // Smoke test: load x86asm and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"x86asm\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeXcompose() throws {
        // Smoke test: load xcompose and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"xcompose\"}")
        _ = try TreeSitterLanguagePack.process(source: "<Multi_key> <a> : \"a\"", config: configObj)
    }

    func testSmokeXml() throws {
        // Smoke test: load xml and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"xml\"}")
        _ = try TreeSitterLanguagePack.process(source: "<?xml version=\"1.0\"?>\n<root>hello</root>", config: configObj)
    }

    func testSmokeYaml() throws {
        // Smoke test: load yaml and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"yaml\"}")
        _ = try TreeSitterLanguagePack.process(source: "key: value", config: configObj)
    }

    func testSmokeYuck() throws {
        // Smoke test: load yuck and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"yuck\"}")
        _ = try TreeSitterLanguagePack.process(source: "(defwidget main [] (label :text \"hi\"))", config: configObj)
    }

    func testSmokeZig() throws {
        // Smoke test: load zig and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"zig\"}")
        _ = try TreeSitterLanguagePack.process(source: "pub fn main() void {}", config: configObj)
    }

    func testSmokeZiggy() throws {
        // Smoke test: load ziggy and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"ziggy\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeZiggySchema() throws {
        // Smoke test: load ziggy_schema and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"ziggy_schema\"}")
        _ = try TreeSitterLanguagePack.process(source: "x", config: configObj)
    }

    func testSmokeZsh() throws {
        // Smoke test: load zsh and parse a simple snippet
        let configObj = try TreeSitterLanguagePack.processConfigFromJson("{\"language\":\"zsh\"}")
        _ = try TreeSitterLanguagePack.process(source: "echo hello", config: configObj)
    }

}
